'use strict';

/**
 * lib/questions.js — AfriQuiz question bank
 * 200 bilingual (FR/EN) questions across 6 categories.
 *
 * Format: Q(category, difficulty, questionFR, questionEN,
 *           [correctFR, correctEN], [wrong1FR, wrong1EN], [wrong2FR, wrong2EN], [wrong3FR, wrong3EN],
 *           explanationFR, explanationEN)
 *
 * NOTE: the CORRECT option is always listed FIRST here; scripts/seed.js
 * shuffles options deterministically before inserting into SQLite.
 *
 * Categories : geo | hist | lang | music | sport | nature
 * Difficulty : easy (5 pts) | medium (10 pts) | hard (20 pts)
 */

function Q(cat, diff, qf, qe, correct, w1, w2, w3, ef, ee) {
  return {
    category: cat,
    difficulty: diff,
    question_fr: qf,
    question_en: qe,
    options: [correct, w1, w2, w3], // [0] is always the correct answer
    explanation_fr: ef,
    explanation_en: ee,
  };
}

const QUESTIONS = [

  /* ═══════════════ 🌍 GÉOGRAPHIE / GEOGRAPHY (35) ═══════════════ */

  Q("geo", "easy",
    "Quel est le plus grand pays d'Afrique en superficie ?",
    "What is the largest country in Africa by land area?",
    ["L'Algérie", "Algeria"], ["Le Nigeria", "Nigeria"], ["L'Égypte", "Egypt"], ["Le Soudan", "Sudan"],
    "L'Algérie couvre environ 2,38 millions de km², devant la RD Congo.",
    "Algeria covers about 2.38 million km², ahead of DR Congo."),

  Q("geo", "easy",
    "Quel est le pays le plus peuplé d'Afrique ?",
    "What is the most populous country in Africa?",
    ["Le Nigeria", "Nigeria"], ["L'Éthiopie", "Ethiopia"], ["L'Égypte", "Egypt"], ["La RD Congo", "DR Congo"],
    "Le Nigeria compte plus de 220 millions d'habitants.",
    "Nigeria has over 220 million inhabitants."),

  Q("geo", "easy",
    "Quelle est la capitale du Mali ?",
    "What is the capital of Mali?",
    ["Bamako", "Bamako"], ["Tombouctou", "Timbuktu"], ["Sikasso", "Sikasso"], ["Gao", "Gao"],
    "Bamako, sur les rives du fleuve Niger, compte plus de 2 millions d'habitants.",
    "Bamako, on the banks of the Niger River, has over 2 million inhabitants."),

  Q("geo", "easy",
    "Quelle est la capitale du Sénégal ?",
    "What is the capital of Senegal?",
    ["Dakar", "Dakar"], ["Saint-Louis", "Saint-Louis"], ["Thiès", "Thiès"], ["Touba", "Touba"],
    "Dakar est la ville la plus à l'ouest du continent africain.",
    "Dakar is the westernmost city on the African continent."),

  Q("geo", "easy",
    "Quelle est la capitale de l'Égypte ?",
    "What is the capital of Egypt?",
    ["Le Caire", "Cairo"], ["Alexandrie", "Alexandria"], ["Gizeh", "Giza"], ["Louxor", "Luxor"],
    "Le Caire est la plus grande métropole du monde arabe.",
    "Cairo is the largest metropolis in the Arab world."),

  Q("geo", "easy",
    "Quelle est la capitale du Ghana ?",
    "What is the capital of Ghana?",
    ["Accra", "Accra"], ["Kumasi", "Kumasi"], ["Tamale", "Tamale"], ["Takoradi", "Takoradi"],
    "Accra est située sur la côte du golfe de Guinée.",
    "Accra lies on the coast of the Gulf of Guinea."),

  Q("geo", "easy",
    "Quelle est la capitale du Kenya ?",
    "What is the capital of Kenya?",
    ["Nairobi", "Nairobi"], ["Mombasa", "Mombasa"], ["Kisumu", "Kisumu"], ["Nakuru", "Nakuru"],
    "Nairobi est la seule capitale au monde avec un parc national en pleine ville.",
    "Nairobi is the only capital in the world with a national park inside the city."),

  Q("geo", "easy",
    "Quelle est la capitale de l'Éthiopie ?",
    "What is the capital of Ethiopia?",
    ["Addis-Abeba", "Addis Ababa"], ["Gondar", "Gondar"], ["Axoum", "Axum"], ["Dire Dawa", "Dire Dawa"],
    "Addis-Abeba signifie « nouvelle fleur » en amharique.",
    "Addis Ababa means 'new flower' in Amharic."),

  Q("geo", "easy",
    "Quel est le plus long fleuve d'Afrique ?",
    "What is the longest river in Africa?",
    ["Le Nil", "The Nile"], ["Le Congo", "The Congo"], ["Le Niger", "The Niger"], ["Le Zambèze", "The Zambezi"],
    "Le Nil parcourt environ 6 650 km à travers 11 pays.",
    "The Nile runs about 6,650 km through 11 countries."),

  Q("geo", "easy",
    "Quel est le plus grand désert d'Afrique ?",
    "What is the largest desert in Africa?",
    ["Le Sahara", "The Sahara"], ["Le Kalahari", "The Kalahari"], ["Le Namib", "The Namib"], ["Le désert de Danakil", "The Danakil Desert"],
    "Le Sahara couvre environ 9 millions de km², presque la taille des États-Unis.",
    "The Sahara covers about 9 million km², nearly the size of the United States."),

  Q("geo", "easy",
    "Quel est le plus haut sommet d'Afrique ?",
    "What is the highest mountain in Africa?",
    ["Le Kilimandjaro", "Mount Kilimanjaro"], ["Le mont Kenya", "Mount Kenya"], ["Le mont Atlas", "The Atlas Mountains"], ["Les monts Simien", "The Simien Mountains"],
    "Le Kilimandjaro culmine à 5 895 m en Tanzanie.",
    "Kilimanjaro rises to 5,895 m in Tanzania."),

  Q("geo", "easy",
    "Quel grand pays insulaire se trouve au large de la côte est africaine ?",
    "Which large island country lies off the east coast of Africa?",
    ["Madagascar", "Madagascar"], ["Maurice", "Mauritius"], ["Les Seychelles", "Seychelles"], ["Les Comores", "Comoros"],
    "Madagascar est la quatrième plus grande île du monde.",
    "Madagascar is the fourth largest island in the world."),

  Q("geo", "easy",
    "Quel est le plus grand lac d'Afrique ?",
    "What is the largest lake in Africa?",
    ["Le lac Victoria", "Lake Victoria"], ["Le lac Tanganyika", "Lake Tanganyika"], ["Le lac Malawi", "Lake Malawi"], ["Le lac Tchad", "Lake Chad"],
    "Le lac Victoria est le deuxième plus grand lac d'eau douce du monde.",
    "Lake Victoria is the second largest freshwater lake in the world."),

  Q("geo", "easy",
    "Quelle est la capitale du Nigeria ?",
    "What is the capital of Nigeria?",
    ["Abuja", "Abuja"], ["Lagos", "Lagos"], ["Kano", "Kano"], ["Ibadan", "Ibadan"],
    "Abuja a remplacé Lagos comme capitale en 1991. Lagos reste la capitale économique.",
    "Abuja replaced Lagos as capital in 1991. Lagos remains the economic hub."),

  Q("geo", "easy",
    "Dans quel pays se trouvent les pyramides de Gizeh ?",
    "In which country are the pyramids of Giza?",
    ["En Égypte", "Egypt"], ["Au Soudan", "Sudan"], ["En Libye", "Libya"], ["Au Maroc", "Morocco"],
    "La grande pyramide de Khéops est la seule merveille du monde antique encore debout.",
    "The Great Pyramid of Khufu is the only ancient world wonder still standing."),

  Q("geo", "medium",
    "Quelle est la capitale administrative de l'Afrique du Sud ?",
    "What is the administrative capital of South Africa?",
    ["Pretoria", "Pretoria"], ["Le Cap", "Cape Town"], ["Johannesburg", "Johannesburg"], ["Durban", "Durban"],
    "L'Afrique du Sud a trois capitales : Pretoria (exécutif), Le Cap (législatif) et Bloemfontein (judiciaire).",
    "South Africa has three capitals: Pretoria (executive), Cape Town (legislative) and Bloemfontein (judicial)."),

  Q("geo", "medium",
    "Quel est le deuxième plus long fleuve d'Afrique ?",
    "What is the second longest river in Africa?",
    ["Le Congo", "The Congo"], ["Le Niger", "The Niger"], ["Le Zambèze", "The Zambezi"], ["L'Orange", "The Orange"],
    "Le fleuve Congo (4 700 km) est aussi le fleuve le plus profond du monde.",
    "The Congo River (4,700 km) is also the deepest river in the world."),

  Q("geo", "medium",
    "Quel fleuve traverse Bamako, la capitale du Mali ?",
    "Which river flows through Bamako, the capital of Mali?",
    ["Le Niger", "The Niger"], ["Le Sénégal", "The Senegal"], ["Le Congo", "The Congo"], ["La Volta", "The Volta"],
    "Le fleuve Niger fait un grand coude de 4 180 km à travers l'Afrique de l'Ouest.",
    "The Niger River makes a great 4,180 km bend across West Africa."),

  Q("geo", "medium",
    "Quel est le lac le plus profond d'Afrique ?",
    "What is the deepest lake in Africa?",
    ["Le lac Tanganyika", "Lake Tanganyika"], ["Le lac Victoria", "Lake Victoria"], ["Le lac Malawi", "Lake Malawi"], ["Le lac Turkana", "Lake Turkana"],
    "Avec 1 470 m de profondeur, c'est le deuxième lac le plus profond du monde après le Baïkal.",
    "At 1,470 m deep, it is the second deepest lake in the world after Baikal."),

  Q("geo", "medium",
    "Sur quel fleuve se trouvent les chutes Victoria ?",
    "On which river are the Victoria Falls?",
    ["Le Zambèze", "The Zambezi"], ["Le Nil", "The Nile"], ["Le Limpopo", "The Limpopo"], ["L'Orange", "The Orange"],
    "Les chutes Victoria, à la frontière Zambie-Zimbabwe, font plus d'un kilomètre de large.",
    "Victoria Falls, on the Zambia-Zimbabwe border, is over a kilometre wide."),

  Q("geo", "medium",
    "Quel est le plus petit pays d'Afrique ?",
    "What is the smallest country in Africa?",
    ["Les Seychelles", "Seychelles"], ["La Gambie", "The Gambia"], ["Les Comores", "Comoros"], ["Maurice", "Mauritius"],
    "Les Seychelles ne couvrent que 455 km². La Gambie est le plus petit pays continental.",
    "Seychelles covers only 455 km². The Gambia is the smallest mainland country."),

  Q("geo", "medium",
    "Quel pays fait partie de la Corne de l'Afrique ?",
    "Which country is part of the Horn of Africa?",
    ["La Somalie", "Somalia"], ["Le Maroc", "Morocco"], ["Le Gabon", "Gabon"], ["La Zambie", "Zambia"],
    "La Corne de l'Afrique comprend la Somalie, l'Éthiopie, l'Érythrée et Djibouti.",
    "The Horn of Africa includes Somalia, Ethiopia, Eritrea and Djibouti."),

  Q("geo", "medium",
    "Dans quel pays se trouve principalement la chaîne de l'Atlas ?",
    "In which country is the Atlas mountain range mainly located?",
    ["Le Maroc", "Morocco"], ["L'Égypte", "Egypt"], ["Le Kenya", "Kenya"], ["L'Angola", "Angola"],
    "Le Toubkal (4 167 m), plus haut sommet de l'Atlas, est le toit de l'Afrique du Nord.",
    "Toubkal (4,167 m), the highest Atlas peak, is the roof of North Africa."),

  Q("geo", "medium",
    "Lequel de ces pays d'Afrique de l'Ouest est enclavé (sans accès à la mer) ?",
    "Which of these West African countries is landlocked?",
    ["Le Burkina Faso", "Burkina Faso"], ["Le Sénégal", "Senegal"], ["Le Ghana", "Ghana"], ["La Guinée", "Guinea"],
    "Le Burkina Faso, le Mali et le Niger sont les trois pays enclavés du Sahel ouest-africain.",
    "Burkina Faso, Mali and Niger are the three landlocked countries of the western Sahel."),

  Q("geo", "medium",
    "Quelle est la capitale du Rwanda ?",
    "What is the capital of Rwanda?",
    ["Kigali", "Kigali"], ["Kampala", "Kampala"], ["Gitega", "Gitega"], ["Dodoma", "Dodoma"],
    "Kigali est réputée comme l'une des villes les plus propres d'Afrique.",
    "Kigali is renowned as one of the cleanest cities in Africa."),

  Q("geo", "medium",
    "Quelle est la capitale du Maroc ?",
    "What is the capital of Morocco?",
    ["Rabat", "Rabat"], ["Casablanca", "Casablanca"], ["Marrakech", "Marrakech"], ["Fès", "Fez"],
    "Casablanca est la plus grande ville, mais Rabat est la capitale politique.",
    "Casablanca is the largest city, but Rabat is the political capital."),

  Q("geo", "medium",
    "Quel détroit sépare l'Afrique de l'Europe ?",
    "Which strait separates Africa from Europe?",
    ["Le détroit de Gibraltar", "The Strait of Gibraltar"], ["Le Bosphore", "The Bosphorus"], ["Le canal de Suez", "The Suez Canal"], ["Bab el-Mandeb", "Bab el-Mandeb"],
    "Seulement 14 km séparent le Maroc de l'Espagne au détroit de Gibraltar.",
    "Only 14 km separate Morocco from Spain at the Strait of Gibraltar."),

  Q("geo", "medium",
    "Quel est le seul pays africain où l'espagnol est langue officielle ?",
    "What is the only African country where Spanish is an official language?",
    ["La Guinée équatoriale", "Equatorial Guinea"], ["Le Maroc", "Morocco"], ["Le Cameroun", "Cameroon"], ["L'Angola", "Angola"],
    "La Guinée équatoriale, ancienne colonie espagnole, est le seul pays hispanophone d'Afrique.",
    "Equatorial Guinea, a former Spanish colony, is the only Spanish-speaking country in Africa."),

  Q("geo", "medium",
    "Combien de pays partagent une frontière avec le Mali ?",
    "How many countries share a border with Mali?",
    ["7", "7"], ["5", "5"], ["4", "4"], ["9", "9"],
    "Algérie, Niger, Burkina Faso, Côte d'Ivoire, Guinée, Sénégal et Mauritanie.",
    "Algeria, Niger, Burkina Faso, Côte d'Ivoire, Guinea, Senegal and Mauritania."),

  Q("geo", "medium",
    "Quelle est la capitale politique de la Côte d'Ivoire ?",
    "What is the political capital of Côte d'Ivoire?",
    ["Yamoussoukro", "Yamoussoukro"], ["Abidjan", "Abidjan"], ["Bouaké", "Bouaké"], ["San-Pédro", "San-Pédro"],
    "Abidjan reste la capitale économique, Yamoussoukro la capitale politique depuis 1983.",
    "Abidjan remains the economic capital; Yamoussoukro has been the political capital since 1983."),

  Q("geo", "medium",
    "Quel pays est entièrement entouré par l'Afrique du Sud ?",
    "Which country is entirely surrounded by South Africa?",
    ["Le Lesotho", "Lesotho"], ["L'Eswatini", "Eswatini"], ["Le Botswana", "Botswana"], ["Le Zimbabwe", "Zimbabwe"],
    "Le Lesotho est aussi le seul pays au monde entièrement situé au-dessus de 1 000 m d'altitude.",
    "Lesotho is also the only country in the world entirely above 1,000 m in elevation."),

  Q("geo", "hard",
    "Quel est le deuxième plus haut sommet d'Afrique ?",
    "What is the second highest mountain in Africa?",
    ["Le mont Kenya", "Mount Kenya"], ["Les monts Rwenzori", "The Rwenzori Mountains"], ["Le Ras Dashen", "Ras Dashen"], ["Le mont Meru", "Mount Meru"],
    "Le mont Kenya culmine à 5 199 m, derrière le Kilimandjaro.",
    "Mount Kenya rises to 5,199 m, behind Kilimanjaro."),

  Q("geo", "hard",
    "Le lac Tchad touche combien de pays ?",
    "How many countries does Lake Chad border?",
    ["4", "4"], ["2", "2"], ["3", "3"], ["6", "6"],
    "Tchad, Niger, Nigeria et Cameroun. Le lac a perdu 90 % de sa surface depuis les années 1960.",
    "Chad, Niger, Nigeria and Cameroon. The lake has lost 90% of its area since the 1960s."),

  Q("geo", "hard",
    "Dans quel pays le Nil Bleu et le Nil Blanc se rejoignent-ils ?",
    "In which country do the Blue Nile and White Nile meet?",
    ["Au Soudan", "Sudan"], ["En Égypte", "Egypt"], ["En Éthiopie", "Ethiopia"], ["En Ouganda", "Uganda"],
    "Les deux Nils se rencontrent à Khartoum, la capitale soudanaise.",
    "The two Niles meet in Khartoum, the Sudanese capital."),

  Q("geo", "hard",
    "Cabinda est une enclave de quel pays africain ?",
    "Cabinda is an exclave of which African country?",
    ["L'Angola", "Angola"], ["La RD Congo", "DR Congo"], ["Le Gabon", "Gabon"], ["Le Congo-Brazzaville", "Republic of the Congo"],
    "Cabinda, riche en pétrole, est séparée de l'Angola par une bande de territoire congolais.",
    "Oil-rich Cabinda is separated from Angola by a strip of Congolese territory."),


  /* ═══════════════ 📜 HISTOIRE / HISTORY (35) ═══════════════ */

  Q("hist", "easy",
    "Mansa Moussa était l'empereur de quel empire ?",
    "Mansa Musa was the emperor of which empire?",
    ["L'empire du Mali", "The Mali Empire"], ["L'empire du Ghana", "The Ghana Empire"], ["L'empire Songhaï", "The Songhai Empire"], ["L'empire d'Éthiopie", "The Ethiopian Empire"],
    "Mansa Moussa (XIVe siècle) est souvent décrit comme l'homme le plus riche de l'histoire.",
    "Mansa Musa (14th century) is often described as the richest man in history."),

  Q("hist", "easy",
    "Qui fut le premier président noir d'Afrique du Sud ?",
    "Who was the first Black president of South Africa?",
    ["Nelson Mandela", "Nelson Mandela"], ["Thabo Mbeki", "Thabo Mbeki"], ["Jacob Zuma", "Jacob Zuma"], ["Frederik de Klerk", "Frederik de Klerk"],
    "Élu en 1994, Nelson Mandela est devenu le symbole mondial de la réconciliation.",
    "Elected in 1994, Nelson Mandela became a global symbol of reconciliation."),

  Q("hist", "easy",
    "Qui a fondé l'empire du Mali au XIIIe siècle ?",
    "Who founded the Mali Empire in the 13th century?",
    ["Soundiata Keïta", "Sundiata Keita"], ["Mansa Moussa", "Mansa Musa"], ["Askia Mohamed", "Askia Muhammad"], ["Sonni Ali Ber", "Sunni Ali"],
    "Soundiata Keïta, le « roi lion », fonda l'empire vers 1235 après sa victoire à Kirina.",
    "Sundiata Keita, the 'lion king', founded the empire around 1235 after his victory at Kirina."),

  Q("hist", "easy",
    "Quelle ville malienne était un grand centre de savoir et de commerce de l'or ?",
    "Which Malian city was a great center of learning and the gold trade?",
    ["Tombouctou", "Timbuktu"], ["Kano", "Kano"], ["Le Caire", "Cairo"], ["Fès", "Fez"],
    "Tombouctou abritait des centaines de milliers de manuscrits et l'université de Sankoré.",
    "Timbuktu held hundreds of thousands of manuscripts and the University of Sankore."),

  Q("hist", "easy",
    "Quel fut le premier pays d'Afrique subsaharienne à obtenir son indépendance, en 1957 ?",
    "Which was the first sub-Saharan African country to gain independence, in 1957?",
    ["Le Ghana", "Ghana"], ["Le Nigeria", "Nigeria"], ["Le Sénégal", "Senegal"], ["Le Kenya", "Kenya"],
    "Le Ghana de Kwame Nkrumah a ouvert la voie aux indépendances africaines.",
    "Kwame Nkrumah's Ghana paved the way for African independences."),

  Q("hist", "easy",
    "Combien d'années Nelson Mandela a-t-il passé en prison ?",
    "How many years did Nelson Mandela spend in prison?",
    ["27 ans", "27 years"], ["10 ans", "10 years"], ["18 ans", "18 years"], ["35 ans", "35 years"],
    "Libéré en 1990 après 27 ans de détention, il fut élu président quatre ans plus tard.",
    "Released in 1990 after 27 years in detention, he was elected president four years later."),

  Q("hist", "easy",
    "Thomas Sankara fut le président de quel pays ?",
    "Thomas Sankara was the president of which country?",
    ["Le Burkina Faso", "Burkina Faso"], ["Le Mali", "Mali"], ["Le Ghana", "Ghana"], ["La Guinée", "Guinea"],
    "Surnommé le « Che Guevara africain », il mena une politique panafricaniste et féministe dès 1983.",
    "Nicknamed the 'African Che Guevara', he led a pan-Africanist and feminist policy from 1983."),

  Q("hist", "easy",
    "Dans quel pays actuel se trouvait l'ancienne cité de Carthage ?",
    "In which modern country was the ancient city of Carthage?",
    ["La Tunisie", "Tunisia"], ["L'Algérie", "Algeria"], ["La Libye", "Libya"], ["L'Égypte", "Egypt"],
    "Carthage, rivale de Rome, fut dirigée par le général Hannibal.",
    "Carthage, Rome's rival, was led by the general Hannibal."),

  Q("hist", "easy",
    "Kwame Nkrumah fut le leader de l'indépendance de quel pays ?",
    "Kwame Nkrumah led the independence of which country?",
    ["Le Ghana", "Ghana"], ["Le Nigeria", "Nigeria"], ["Le Kenya", "Kenya"], ["La Tanzanie", "Tanzania"],
    "Nkrumah, père du panafricanisme, devint le premier président du Ghana en 1960.",
    "Nkrumah, father of pan-Africanism, became Ghana's first president in 1960."),

  Q("hist", "easy",
    "Quelle puissance coloniale a colonisé l'Algérie ?",
    "Which colonial power colonized Algeria?",
    ["La France", "France"], ["L'Italie", "Italy"], ["L'Espagne", "Spain"], ["Le Royaume-Uni", "The United Kingdom"],
    "L'Algérie fut française de 1830 à 1962, date de son indépendance après une guerre de 8 ans.",
    "Algeria was French from 1830 to 1962, when it gained independence after an 8-year war."),

  Q("hist", "medium",
    "En quelle année le Mali a-t-il obtenu son indépendance ?",
    "In which year did Mali gain its independence?",
    ["1960", "1960"], ["1957", "1957"], ["1962", "1962"], ["1958", "1958"],
    "Le Mali est devenu indépendant le 22 septembre 1960, après l'éphémère Fédération du Mali avec le Sénégal.",
    "Mali became independent on September 22, 1960, after the short-lived Mali Federation with Senegal."),

  Q("hist", "medium",
    "Thomas Sankara a rebaptisé la Haute-Volta en...",
    "Thomas Sankara renamed Upper Volta to...",
    ["Burkina Faso", "Burkina Faso"], ["Mali", "Mali"], ["Bénin", "Benin"], ["Niger", "Niger"],
    "Le changement de nom eut lieu en 1984, un an après son arrivée au pouvoir.",
    "The name change took place in 1984, one year after he came to power."),

  Q("hist", "medium",
    "Que signifie « Burkina Faso » ?",
    "What does 'Burkina Faso' mean?",
    ["Le pays des hommes intègres", "The land of upright people"], ["La terre des lions", "The land of lions"], ["Le pays du fleuve", "The land of the river"], ["La terre rouge", "The red land"],
    "Le nom combine des mots mooré et dioula : « burkina » (intègre) et « faso » (patrie).",
    "The name combines Mooré and Dioula words: 'burkina' (upright) and 'faso' (homeland)."),

  Q("hist", "medium",
    "Quelle était la capitale de l'empire Songhaï ?",
    "What was the capital of the Songhai Empire?",
    ["Gao", "Gao"], ["Tombouctou", "Timbuktu"], ["Djenné", "Djenné"], ["Kano", "Kano"],
    "L'empire Songhaï (XVe-XVIe siècle) fut l'un des plus grands empires de l'histoire africaine.",
    "The Songhai Empire (15th-16th century) was one of the largest empires in African history."),

  Q("hist", "medium",
    "Quel empereur du Mali fit un célèbre pèlerinage à La Mecque en 1324, distribuant de l'or ?",
    "Which Mali emperor made a famous pilgrimage to Mecca in 1324, handing out gold?",
    ["Mansa Moussa", "Mansa Musa"], ["Soundiata Keïta", "Sundiata Keita"], ["Askia Mohamed", "Askia Muhammad"], ["Sonni Ali Ber", "Sunni Ali"],
    "Sa distribution d'or au Caire fit chuter le prix du métal précieux pendant des années.",
    "His gold handouts in Cairo drove down the price of the precious metal for years."),

  Q("hist", "medium",
    "Askia Mohamed fut le grand souverain de quel empire ?",
    "Askia Muhammad was the great ruler of which empire?",
    ["L'empire Songhaï", "The Songhai Empire"], ["L'empire du Mali", "The Mali Empire"], ["L'empire du Ghana", "The Ghana Empire"], ["Le Kanem-Bornou", "Kanem-Bornu"],
    "Sous Askia Mohamed, Tombouctou devint la capitale intellectuelle du monde musulman ouest-africain.",
    "Under Askia Muhammad, Timbuktu became the intellectual capital of the West African Muslim world."),

  Q("hist", "medium",
    "Qui fut le premier Premier ministre du Congo indépendant, assassiné en 1961 ?",
    "Who was the first Prime Minister of independent Congo, assassinated in 1961?",
    ["Patrice Lumumba", "Patrice Lumumba"], ["Mobutu Sese Seko", "Mobutu Sese Seko"], ["Joseph Kasa-Vubu", "Joseph Kasa-Vubu"], ["Moïse Tshombe", "Moise Tshombe"],
    "Lumumba reste un héros du panafricanisme ; une place de Bamako porte son nom.",
    "Lumumba remains a pan-Africanist hero; a square in Bamako bears his name."),

  Q("hist", "medium",
    "Quel empereur d'Éthiopie est devenu une icône du mouvement rastafari ?",
    "Which emperor of Ethiopia became an icon of the Rastafari movement?",
    ["Haïlé Sélassié", "Haile Selassie"], ["Ménélik II", "Menelik II"], ["Tewodros II", "Tewodros II"], ["Mengistu Haile Mariam", "Mengistu Haile Mariam"],
    "Son nom de naissance, Ras Tafari Makonnen, a donné son nom au mouvement.",
    "His birth name, Ras Tafari Makonnen, gave the movement its name."),

  Q("hist", "medium",
    "Quelle bataille de 1896 vit l'Éthiopie écraser l'armée italienne ?",
    "Which 1896 battle saw Ethiopia crush the Italian army?",
    ["La bataille d'Adoua", "The Battle of Adwa"], ["La bataille d'Axoum", "The Battle of Axum"], ["La bataille de Gondar", "The Battle of Gondar"], ["La bataille d'Harar", "The Battle of Harar"],
    "Adoua fit de l'Éthiopie le seul pays africain à avoir repoussé durablement la colonisation.",
    "Adwa made Ethiopia the only African country to have durably repelled colonization."),

  Q("hist", "medium",
    "En quelles années la conférence de Berlin a-t-elle partagé l'Afrique entre puissances européennes ?",
    "In which years did the Berlin Conference partition Africa among European powers?",
    ["1884-1885", "1884-1885"], ["1914-1918", "1914-1918"], ["1945-1946", "1945-1946"], ["1870-1871", "1870-1871"],
    "Aucun Africain n'était présent à la table lorsque les frontières du continent furent tracées.",
    "No African was at the table when the continent's borders were drawn."),

  Q("hist", "medium",
    "Sur quelle île-prison Nelson Mandela a-t-il passé la majeure partie de sa détention ?",
    "On which prison island did Nelson Mandela spend most of his detention?",
    ["Robben Island", "Robben Island"], ["L'île de Gorée", "Gorée Island"], ["Zanzibar", "Zanzibar"], ["Sainte-Hélène", "Saint Helena"],
    "Robben Island, au large du Cap, est aujourd'hui un musée classé à l'UNESCO.",
    "Robben Island, off Cape Town, is now a UNESCO-listed museum."),

  Q("hist", "medium",
    "Sankoré, à Tombouctou, était surtout célèbre comme...",
    "Sankore, in Timbuktu, was mainly famous as a...",
    ["Grande université", "Great university"], ["Palais royal", "Royal palace"], ["Port fluvial", "River port"], ["Forteresse militaire", "Military fortress"],
    "L'université de Sankoré accueillait jusqu'à 25 000 étudiants à son apogée.",
    "The University of Sankore hosted up to 25,000 students at its peak."),

  Q("hist", "medium",
    "Dans quelle ville se trouve le siège de l'Union africaine ?",
    "In which city is the African Union headquartered?",
    ["Addis-Abeba", "Addis Ababa"], ["Nairobi", "Nairobi"], ["Abuja", "Abuja"], ["Johannesburg", "Johannesburg"],
    "Le siège de l'UA se trouve à Addis-Abeba, la « capitale diplomatique » de l'Afrique.",
    "The AU headquarters is in Addis Ababa, Africa's 'diplomatic capital'."),

  Q("hist", "medium",
    "Quelle organisation, fondée en 1963 à Addis-Abeba, a précédé l'Union africaine ?",
    "Which organization, founded in 1963 in Addis Ababa, preceded the African Union?",
    ["L'OUA (Organisation de l'unité africaine)", "The OAU (Organization of African Unity)"], ["La CEDEAO", "ECOWAS"], ["La SADC", "SADC"], ["L'Union du Maghreb arabe", "The Arab Maghreb Union"],
    "L'OUA est devenue l'Union africaine en 2002 à Durban.",
    "The OAU became the African Union in 2002 in Durban."),

  Q("hist", "medium",
    "La cité médiévale de pierre du Grand Zimbabwe se trouve dans quel pays actuel ?",
    "The medieval stone city of Great Zimbabwe is in which modern country?",
    ["Le Zimbabwe", "Zimbabwe"], ["La Zambie", "Zambia"], ["Le Mozambique", "Mozambique"], ["Le Botswana", "Botswana"],
    "Le pays a pris le nom de cette cité, qui signifie « maisons de pierre » en shona.",
    "The country took its name from this city, which means 'houses of stone' in Shona."),

  Q("hist", "medium",
    "En quelle année les premières élections multiraciales ont-elles mis fin à l'apartheid ?",
    "In which year did the first multiracial elections end apartheid?",
    ["1994", "1994"], ["1990", "1990"], ["1989", "1989"], ["2000", "2000"],
    "Le 27 avril 1994, des millions de Sud-Africains noirs votèrent pour la première fois.",
    "On April 27, 1994, millions of Black South Africans voted for the first time."),

  Q("hist", "medium",
    "En quelle année eut lieu le massacre de Sharpeville en Afrique du Sud ?",
    "In which year did the Sharpeville massacre take place in South Africa?",
    ["1960", "1960"], ["1976", "1976"], ["1948", "1948"], ["1994", "1994"],
    "69 manifestants pacifiques furent tués le 21 mars 1960, devenu la Journée internationale contre le racisme.",
    "69 peaceful protesters were killed on March 21, 1960, now the International Day Against Racism."),

  Q("hist", "medium",
    "L'Algérie a obtenu son indépendance en 1962 après une guerre contre quel pays ?",
    "Algeria gained independence in 1962 after a war against which country?",
    ["La France", "France"], ["L'Espagne", "Spain"], ["L'Italie", "Italy"], ["Le Portugal", "Portugal"],
    "La guerre d'Algérie (1954-1962) s'est terminée par les accords d'Évian.",
    "The Algerian War (1954-1962) ended with the Évian Accords."),

  Q("hist", "hard",
    "Le royaume de Koush a érigé ses pyramides à Méroé, dans quel pays actuel ?",
    "The Kingdom of Kush built its pyramids at Meroë, in which modern country?",
    ["Le Soudan", "Sudan"], ["L'Égypte", "Egypt"], ["L'Éthiopie", "Ethiopia"], ["Le Tchad", "Chad"],
    "Le Soudan compte plus de 200 pyramides, davantage que l'Égypte.",
    "Sudan has over 200 pyramids, more than Egypt."),

  Q("hist", "hard",
    "Yaa Asantewaa, qui mena la guerre contre les Britanniques en 1900, était reine-mère de quel peuple ?",
    "Yaa Asantewaa, who led the war against the British in 1900, was queen mother of which people?",
    ["Les Ashantis", "The Ashanti"], ["Les Zoulous", "The Zulu"], ["Les Yorubas", "The Yoruba"], ["Les Peuls", "The Fulani"],
    "Elle mena la guerre du Trône d'or au Ghana, devenant une icône de la résistance africaine.",
    "She led the War of the Golden Stool in Ghana, becoming an icon of African resistance."),

  Q("hist", "hard",
    "Amílcar Cabral a mené la lutte d'indépendance de quel pays ?",
    "Amílcar Cabral led the independence struggle of which country?",
    ["La Guinée-Bissau", "Guinea-Bissau"], ["L'Angola", "Angola"], ["Le Mozambique", "Mozambique"], ["Le Sénégal", "Senegal"],
    "Cabral, également penseur majeur du panafricanisme, lutta pour la Guinée-Bissau et le Cap-Vert.",
    "Cabral, also a major pan-Africanist thinker, fought for Guinea-Bissau and Cape Verde."),

  Q("hist", "hard",
    "Quelle bataille de 1235 permit à Soundiata Keïta de fonder l'empire du Mali ?",
    "Which 1235 battle allowed Sundiata Keita to found the Mali Empire?",
    ["La bataille de Kirina", "The Battle of Kirina"], ["La bataille de Koulikoro", "The Battle of Koulikoro"], ["La bataille de Tabon", "The Battle of Tabon"], ["La bataille de Kita", "The Battle of Kita"],
    "À Kirina, Soundiata vainquit le roi-sorcier Soumaoro Kanté et unifia le Manden.",
    "At Kirina, Sundiata defeated the sorcerer-king Soumaoro Kanté and unified the Manden."),

  Q("hist", "hard",
    "Le Liberia fut fondé au XIXe siècle par...",
    "Liberia was founded in the 19th century by...",
    ["D'anciens esclaves affranchis des États-Unis", "Freed slaves from the United States"], ["Des colons français", "French settlers"], ["Des commerçants portugais", "Portuguese traders"], ["Des missionnaires britanniques", "British missionaries"],
    "Sa capitale, Monrovia, porte le nom du président américain James Monroe.",
    "Its capital, Monrovia, is named after US President James Monroe."),

  Q("hist", "hard",
    "Quel pays africain possède le plus grand nombre de pyramides ?",
    "Which African country has the largest number of pyramids?",
    ["Le Soudan", "Sudan"], ["L'Égypte", "Egypt"], ["La Libye", "Libya"], ["L'Éthiopie", "Ethiopia"],
    "Les pyramides nubiennes de Méroé, plus petites mais plus nombreuses, dépassent les 200.",
    "The Nubian pyramids of Meroë, smaller but more numerous, exceed 200."),

  Q("hist", "hard",
    "Wagadu est l'autre nom de quel empire ouest-africain ?",
    "Wagadu is another name for which West African empire?",
    ["L'empire du Ghana", "The Ghana Empire"], ["L'empire du Mali", "The Mali Empire"], ["L'empire Songhaï", "The Songhai Empire"], ["Le Kanem-Bornou", "Kanem-Bornu"],
    "L'empire du Ghana (Wagadu) contrôlait le commerce de l'or et du sel dès le VIIIe siècle.",
    "The Ghana Empire (Wagadu) controlled the gold and salt trade from the 8th century."),


  /* ═══════════════ 🗣️ LANGUES / LANGUAGES (30) ═══════════════ */

  Q("lang", "easy",
    "Comment dit-on « bonjour » en swahili ?",
    "How do you say 'hello' in Swahili?",
    ["Jambo", "Jambo"], ["Asante", "Asante"], ["Rafiki", "Rafiki"], ["Simba", "Simba"],
    "On dit aussi « Habari ». Le swahili est parlé par plus de 100 millions de personnes.",
    "You can also say 'Habari'. Swahili is spoken by over 100 million people."),

  Q("lang", "easy",
    "Comment dit-on « merci » en swahili ?",
    "How do you say 'thank you' in Swahili?",
    ["Asante", "Asante"], ["Jambo", "Jambo"], ["Karibu", "Karibu"], ["Kwaheri", "Kwaheri"],
    "« Asante sana » signifie « merci beaucoup ».",
    "'Asante sana' means 'thank you very much'."),

  Q("lang", "easy",
    "Que signifie l'expression swahilie « Hakuna matata » ?",
    "What does the Swahili phrase 'Hakuna matata' mean?",
    ["Pas de souci", "No worries"], ["Bienvenue", "Welcome"], ["Bonne nuit", "Good night"], ["À demain", "See you tomorrow"],
    "Rendue célèbre par Le Roi Lion, c'est une expression courante en Afrique de l'Est.",
    "Made famous by The Lion King, it is a common phrase in East Africa."),

  Q("lang", "easy",
    "Que signifie « simba » en swahili ?",
    "What does 'simba' mean in Swahili?",
    ["Lion", "Lion"], ["Éléphant", "Elephant"], ["Tigre", "Tiger"], ["Zèbre", "Zebra"],
    "C'est le nom du héros du Roi Lion. L'équipe de Tanzanie s'appelle d'ailleurs les Taifa Stars, mais Simba est aussi un grand club de Dar es Salaam.",
    "It is the name of The Lion King's hero. Simba is also a major club in Dar es Salaam."),

  Q("lang", "easy",
    "Quelle est la langue la plus parlée au Mali ?",
    "What is the most widely spoken language in Mali?",
    ["Le bambara", "Bambara"], ["Le français", "French"], ["Le peul", "Fula"], ["Le soninké", "Soninke"],
    "Le bambara est compris par environ 80 % des Maliens, bien que le français soit la langue administrative.",
    "Bambara is understood by about 80% of Malians, though French is the administrative language."),

  Q("lang", "easy",
    "Quelle langue sud-africaine est célèbre pour ses consonnes cliquées ?",
    "Which South African language is famous for its click consonants?",
    ["Le xhosa", "Xhosa"], ["Le swahili", "Swahili"], ["Le haoussa", "Hausa"], ["Le wolof", "Wolof"],
    "Le xhosa et le zoulou utilisent des clics, hérités des langues khoisan. Nelson Mandela était xhosa.",
    "Xhosa and Zulu use clicks inherited from Khoisan languages. Nelson Mandela was Xhosa."),

  Q("lang", "easy",
    "Quelle est la langue de travail fédérale de l'Éthiopie ?",
    "What is the federal working language of Ethiopia?",
    ["L'amharique", "Amharic"], ["Le swahili", "Swahili"], ["L'arabe", "Arabic"], ["Le somali", "Somali"],
    "L'amharique possède son propre alphabet, le fidel, dérivé du guèze.",
    "Amharic has its own script, the fidel, derived from Ge'ez."),

  Q("lang", "easy",
    "Quelle langue est surtout parlée dans le nord du Nigeria et au Niger ?",
    "Which language is mainly spoken in northern Nigeria and Niger?",
    ["Le haoussa", "Hausa"], ["Le yoruba", "Yoruba"], ["L'igbo", "Igbo"], ["Le wolof", "Wolof"],
    "Le haoussa est l'une des langues les plus parlées d'Afrique, avec plus de 50 millions de locuteurs.",
    "Hausa is one of Africa's most spoken languages, with over 50 million speakers."),

  Q("lang", "easy",
    "Comment dit-on « merci » en bambara ?",
    "How do you say 'thank you' in Bambara?",
    ["I ni ce", "I ni ce"], ["I ni sogoma", "I ni sogoma"], ["Hɛrɛ", "Hɛrɛ"], ["Awa", "Awa"],
    "« I ni ce » sert aussi à répondre aux salutations. « Hɛrɛ » signifie « paix ».",
    "'I ni ce' is also used to answer greetings. 'Hɛrɛ' means 'peace'."),

  Q("lang", "easy",
    "Que signifie « rafiki » en swahili ?",
    "What does 'rafiki' mean in Swahili?",
    ["Ami", "Friend"], ["Frère", "Brother"], ["Lion", "Lion"], ["Soleil", "Sun"],
    "Rafiki est le nom du sage mandrill dans Le Roi Lion.",
    "Rafiki is the wise mandrill in The Lion King."),

  Q("lang", "easy",
    "Comment dit-on « bienvenue » en swahili ?",
    "How do you say 'welcome' in Swahili?",
    ["Karibu", "Karibu"], ["Asante", "Asante"], ["Kwaheri", "Kwaheri"], ["Pole", "Pole"],
    "« Karibu sana » : « soyez le bienvenu ». Les Kenyans sont réputés pour leur accueil chaleureux.",
    "'Karibu sana': 'you are very welcome'. Kenyans are known for their warm hospitality."),

  Q("lang", "easy",
    "L'arabe est une langue officielle de quel pays d'Afrique du Nord ?",
    "Arabic is an official language of which North African country?",
    ["Le Maroc", "Morocco"], ["Le Nigeria", "Nigeria"], ["Le Kenya", "Kenya"], ["L'Afrique du Sud", "South Africa"],
    "L'arabe est officiel dans plus de 10 pays africains, du Maroc à l'Égypte.",
    "Arabic is official in more than 10 African countries, from Morocco to Egypt."),

  Q("lang", "medium",
    "Dans quel pays le swahili est-il une langue officielle ?",
    "In which country is Swahili an official language?",
    ["Le Kenya", "Kenya"], ["Le Nigeria", "Nigeria"], ["Le Maroc", "Morocco"], ["L'Égypte", "Egypt"],
    "Le swahili est officiel au Kenya, en Tanzanie, en Ouganda et en RD Congo, et langue de l'Union africaine.",
    "Swahili is official in Kenya, Tanzania, Uganda and DR Congo, and is an African Union language."),

  Q("lang", "medium",
    "Le wolof est principalement parlé dans quel pays ?",
    "Wolof is mainly spoken in which country?",
    ["Le Sénégal", "Senegal"], ["Le Mali", "Mali"], ["Le Ghana", "Ghana"], ["Le Nigeria", "Nigeria"],
    "Le wolof est la langue de la vie quotidienne à Dakar, bien plus que le français.",
    "Wolof is the language of daily life in Dakar, far more than French."),

  Q("lang", "medium",
    "Le lingala est principalement parlé dans quel pays ?",
    "Lingala is mainly spoken in which country?",
    ["La RD Congo", "DR Congo"], ["Le Kenya", "Kenya"], ["L'Éthiopie", "Ethiopia"], ["Le Sénégal", "Senegal"],
    "Le lingala est la langue de la rumba congolaise et de l'armée.",
    "Lingala is the language of Congolese rumba and of the army."),

  Q("lang", "medium",
    "Le yoruba est principalement parlé dans quel pays ?",
    "Yoruba is mainly spoken in which country?",
    ["Le Nigeria", "Nigeria"], ["Le Ghana", "Ghana"], ["Le Sénégal", "Senegal"], ["Le Congo", "Congo"],
    "Le yoruba compte plus de 40 millions de locuteurs, du Nigeria au Bénin, et une diaspora immense.",
    "Yoruba has over 40 million speakers, from Nigeria to Benin, and a huge diaspora."),

  Q("lang", "medium",
    "Combien de langues environ sont parlées sur le continent africain ?",
    "About how many languages are spoken on the African continent?",
    ["Environ 2 000", "About 2,000"], ["Environ 200", "About 200"], ["Environ 500", "About 500"], ["Plus de 10 000", "Over 10,000"],
    "L'Afrique est le continent le plus diversifié linguistiquement : près d'un tiers des langues du monde.",
    "Africa is the most linguistically diverse continent: nearly a third of the world's languages."),

  Q("lang", "medium",
    "Combien de langues environ sont parlées au Nigeria ?",
    "About how many languages are spoken in Nigeria?",
    ["Plus de 500", "Over 500"], ["Environ 50", "About 50"], ["Environ 100", "About 100"], ["Environ 20", "About 20"],
    "Le Nigeria est l'un des pays les plus multilingues du monde : haoussa, yoruba, igbo et des centaines d'autres.",
    "Nigeria is one of the most multilingual countries in the world: Hausa, Yoruba, Igbo and hundreds more."),

  Q("lang", "medium",
    "Comment dit-on « bonjour » (le matin) en bambara ?",
    "How do you say 'good morning' in Bambara?",
    ["I ni sogoma", "I ni sogoma"], ["I ni ce", "I ni ce"], ["I ni wula", "I ni wula"], ["Hɛrɛ sira", "Hɛrɛ sira"],
    "« I ni sogoma » salue le matin, « i ni wula » l'après-midi. On répond souvent « n ba ».",
    "'I ni sogoma' greets the morning, 'i ni wula' the afternoon. People often answer 'n ba'."),

  Q("lang", "medium",
    "Que signifie le mot bambara « ji » ?",
    "What does the Bambara word 'ji' mean?",
    ["L'eau", "Water"], ["Le village", "The village"], ["L'enfant", "The child"], ["La femme", "The woman"],
    "Le fleuve Niger est appelé « Joliba », « le grand fleuve », en langues mandingues.",
    "The Niger River is called 'Joliba', 'the great river', in Manding languages."),

  Q("lang", "medium",
    "Le portugais est langue officielle de quel pays africain ?",
    "Portuguese is an official language of which African country?",
    ["Le Mozambique", "Mozambique"], ["Le Sénégal", "Senegal"], ["Le Kenya", "Kenya"], ["Le Ghana", "Ghana"],
    "Angola, Mozambique, Cap-Vert, Guinée-Bissau et São Tomé forment les pays lusophones d'Afrique.",
    "Angola, Mozambique, Cape Verde, Guinea-Bissau and São Tomé form Africa's lusophone countries."),

  Q("lang", "medium",
    "Comment s'appelle l'écriture de la langue amharique ?",
    "What is the script of the Amharic language called?",
    ["Le fidel (guèze)", "The fidel (Ge'ez)"], ["L'arabe", "Arabic"], ["L'alphabet latin", "The Latin alphabet"], ["Le tifinagh", "Tifinagh"],
    "Le fidel est un abugida unique : chaque caractère combine une consonne et une voyelle.",
    "The fidel is a unique abugida: each character combines a consonant and a vowel."),

  Q("lang", "medium",
    "Le tifinagh est l'écriture traditionnelle de quel peuple ?",
    "Tifinagh is the traditional script of which people?",
    ["Les Touaregs (berbères)", "The Tuareg (Berbers)"], ["Les Éthiopiens", "Ethiopians"], ["Les Swahilis", "The Swahili"], ["Les Zoulous", "The Zulu"],
    "Le tifinagh, alphabet ancien des Berbères, est redevenu officiel au Maroc et en Algérie.",
    "Tifinagh, the ancient Berber alphabet, has become official again in Morocco and Algeria."),

  Q("lang", "medium",
    "Comment s'appelle la langue du peuple peul, parlée à travers toute l'Afrique de l'Ouest ?",
    "What is the language of the Fulani people, spoken across West Africa?",
    ["Le fulfuldé (peul)", "Fulfulde (Fula)"], ["Le wolof", "Wolof"], ["Le bambara", "Bambara"], ["Le soninké", "Soninke"],
    "Les Peuls sont le plus grand peuple nomade du monde, du Sénégal au Soudan.",
    "The Fulani are the world's largest nomadic people, from Senegal to Sudan."),

  Q("lang", "medium",
    "Que répond-on à la salutation « As-salamu alaykum » ?",
    "What is the reply to the greeting 'As-salamu alaykum'?",
    ["Wa alaykum as-salam", "Wa alaykum as-salam"], ["Hamdoulillah", "Alhamdulillah"], ["Inch'Allah", "Insha'Allah"], ["Aw ni ce", "Aw ni ce"],
    "« Que la paix soit aussi sur toi » : une salutation universelle au Sahel, du Mali au Sénégal.",
    "'And peace be upon you too': a universal greeting in the Sahel, from Mali to Senegal."),

  Q("lang", "hard",
    "« Kiswahili » est le nom local de quelle langue ?",
    "'Kiswahili' is the native name of which language?",
    ["Le swahili", "Swahili"], ["Le zoulou", "Zulu"], ["Le lingala", "Lingala"], ["Le créole", "Creole"],
    "En swahili, « ki- » est le préfixe des langues : Kiswahili, Kiingereza (anglais)...",
    "In Swahili, 'ki-' is the language prefix: Kiswahili, Kiingereza (English)..."),

  Q("lang", "hard",
    "Le bambara, le malinké et le dioula appartiennent à quelle famille de langues ?",
    "Bambara, Malinké and Dioula belong to which language family?",
    ["Les langues mandées", "The Mande languages"], ["Les langues bantoues", "The Bantu languages"], ["Les langues nilotiques", "The Nilotic languages"], ["Les langues khoisan", "The Khoisan languages"],
    "Ces langues mandées sont si proches qu'elles sont mutuellement intelligibles du Mali à la Côte d'Ivoire.",
    "These Mande languages are so close they are mutually intelligible from Mali to Côte d'Ivoire."),

  Q("lang", "hard",
    "Les langues bantoues sont majoritairement parlées dans quelle région ?",
    "Bantu languages are mostly spoken in which region?",
    ["Afrique centrale, orientale et australe", "Central, eastern and southern Africa"], ["Afrique du Nord", "North Africa"], ["La Corne de l'Afrique", "The Horn of Africa"], ["Le Sahel", "The Sahel"],
    "Du swahili au zoulou, les langues bantoues couvrent près de la moitié du continent.",
    "From Swahili to Zulu, Bantu languages cover nearly half the continent."),

  Q("lang", "hard",
    "Combien de langues officielles l'Afrique du Sud reconnaît-elle depuis 2023 ?",
    "How many official languages has South Africa recognized since 2023?",
    ["12", "12"], ["2", "2"], ["5", "5"], ["21", "21"],
    "La langue des signes sud-africaine est devenue la 12e langue officielle en 2023.",
    "South African Sign Language became the 12th official language in 2023."),

  Q("lang", "hard",
    "Le mot « ubuntu » (« je suis parce que nous sommes ») vient de quelle famille de langues ?",
    "The word 'ubuntu' ('I am because we are') comes from which language family?",
    ["Les langues nguni (zoulou, xhosa)", "The Nguni languages (Zulu, Xhosa)"], ["Les langues mandées", "The Mande languages"], ["Les langues sémitiques", "The Semitic languages"], ["Les langues nilotiques", "The Nilotic languages"],
    "L'ubuntu, philosophie de l'humanité partagée, a inspiré Mandela et Tutu.",
    "Ubuntu, the philosophy of shared humanity, inspired Mandela and Tutu."),

  /* ═══════════════ 🎵 MUSIQUE / MUSIC (30) ═══════════════ */

  Q("music", "easy",
    "De quel pays vient Fela Kuti ?",
    "Which country is Fela Kuti from?",
    ["Le Nigeria", "Nigeria"], ["Le Ghana", "Ghana"], ["Le Sénégal", "Senegal"], ["Le Congo", "Congo"],
    "Musicien et activiste, Fela a défié les dictatures nigérianes toute sa vie.",
    "A musician and activist, Fela defied Nigerian dictatorships all his life."),

  Q("music", "easy",
    "Quel genre musical Fela Kuti a-t-il inventé ?",
    "Which music genre did Fela Kuti invent?",
    ["L'afrobeat", "Afrobeat"], ["Le highlife", "Highlife"], ["Le mbalax", "Mbalax"], ["L'amapiano", "Amapiano"],
    "L'afrobeat (sans s !) mélange jazz, funk et rythmes yoruba. À ne pas confondre avec les afrobeats actuels.",
    "Afrobeat (no s!) blends jazz, funk and Yoruba rhythms. Not to be confused with today's afrobeats."),

  Q("music", "easy",
    "De quel pays vient Youssou N'Dour ?",
    "Which country is Youssou N'Dour from?",
    ["Le Sénégal", "Senegal"], ["Le Mali", "Mali"], ["La Côte d'Ivoire", "Côte d'Ivoire"], ["La Guinée", "Guinea"],
    "Youssou N'Dour, star mondiale du mbalax, a même été ministre de la Culture sénégalais.",
    "Youssou N'Dour, world star of mbalax, even served as Senegal's Minister of Culture."),

  Q("music", "easy",
    "De quel pays vient Salif Keita, la « voix d'or de l'Afrique » ?",
    "Which country is Salif Keita, the 'golden voice of Africa', from?",
    ["Le Mali", "Mali"], ["Le Sénégal", "Senegal"], ["Le Burkina Faso", "Burkina Faso"], ["Le Niger", "Niger"],
    "Descendant direct de Soundiata Keïta, albinos, il a brisé les tabous avec sa voix légendaire.",
    "A direct descendant of Sundiata Keita, born with albinism, he broke taboos with his legendary voice."),

  Q("music", "easy",
    "Quelle chanteuse était surnommée « Mama Africa » ?",
    "Which singer was nicknamed 'Mama Africa'?",
    ["Miriam Makeba", "Miriam Makeba"], ["Angélique Kidjo", "Angelique Kidjo"], ["Oumou Sangaré", "Oumou Sangare"], ["Cesária Évora", "Cesaria Evora"],
    "Exilée d'Afrique du Sud par l'apartheid, elle a porté la voix du continent dans le monde entier.",
    "Exiled from South Africa by apartheid, she carried the continent's voice around the world."),

  Q("music", "easy",
    "Qu'est-ce que la kora ?",
    "What is the kora?",
    ["Une harpe-luth à 21 cordes", "A 21-string harp-lute"], ["Un tambour", "A drum"], ["Une flûte", "A flute"], ["Une trompette", "A trumpet"],
    "La kora, instrument des griots mandingues, est taillée dans une calebasse.",
    "The kora, instrument of Manding griots, is carved from a calabash."),

  Q("music", "easy",
    "Qu'est-ce que le djembé ?",
    "What is the djembe?",
    ["Un tambour", "A drum"], ["Une guitare", "A guitar"], ["Une flûte", "A flute"], ["Une harpe", "A harp"],
    "Né chez les Manden (Mali, Guinée), le djembé est devenu le tambour le plus joué au monde.",
    "Born among the Manden people (Mali, Guinea), the djembe has become the world's most played drum."),

  Q("music", "easy",
    "De quel pays vient Burna Boy ?",
    "Which country is Burna Boy from?",
    ["Le Nigeria", "Nigeria"], ["Le Ghana", "Ghana"], ["L'Afrique du Sud", "South Africa"], ["Le Kenya", "Kenya"],
    "Burna Boy, « African Giant », a remporté un Grammy Award en 2021.",
    "Burna Boy, 'African Giant', won a Grammy Award in 2021."),

  Q("music", "easy",
    "De quel pays vient Angélique Kidjo ?",
    "Which country is Angelique Kidjo from?",
    ["Le Bénin", "Benin"], ["Le Togo", "Togo"], ["Le Ghana", "Ghana"], ["Le Nigeria", "Nigeria"],
    "Angélique Kidjo a remporté cinq Grammy Awards, record pour une artiste africaine.",
    "Angelique Kidjo has won five Grammy Awards, a record for an African artist."),

  Q("music", "easy",
    "D'où vient le genre amapiano ?",
    "Where does the amapiano genre come from?",
    ["L'Afrique du Sud", "South Africa"], ["Le Nigeria", "Nigeria"], ["Le Kenya", "Kenya"], ["L'Angola", "Angola"],
    "Né dans les townships sud-africaines, l'amapiano (« les pianos » en zoulou) a conquis la planète.",
    "Born in South African townships, amapiano ('the pianos' in Zulu) has taken over the planet."),

  Q("music", "medium",
    "Le mbalax est le genre musical emblématique de quel pays ?",
    "Mbalax is the signature music genre of which country?",
    ["Le Sénégal", "Senegal"], ["Le Mali", "Mali"], ["Le Congo", "Congo"], ["Le Cameroun", "Cameroon"],
    "Youssou N'Dour et le Super Étoile de Dakar ont porté le mbalax sur la scène mondiale.",
    "Youssou N'Dour and Super Étoile de Dakar carried mbalax onto the world stage."),

  Q("music", "medium",
    "Le highlife est né dans quel pays ?",
    "Highlife was born in which country?",
    ["Le Ghana", "Ghana"], ["Le Nigeria", "Nigeria"], ["Le Mali", "Mali"], ["L'Éthiopie", "Ethiopia"],
    "Né dans les années 1920 au Ghana, le highlife a influencé toute la musique ouest-africaine.",
    "Born in 1920s Ghana, highlife influenced all of West African music."),

  Q("music", "medium",
    "Le coupé-décalé est un genre venu de quel pays ?",
    "Coupé-décalé is a genre from which country?",
    ["La Côte d'Ivoire", "Côte d'Ivoire"], ["Le Sénégal", "Senegal"], ["La RD Congo", "DR Congo"], ["Le Gabon", "Gabon"],
    "Né dans les années 2000, le coupé-décalé fait danser Abidjan et toute l'Afrique de l'Ouest.",
    "Born in the 2000s, coupé-décalé gets Abidjan and all of West Africa dancing."),

  Q("music", "medium",
    "Quel instrument jouait Ali Farka Touré, maître du blues du désert ?",
    "Which instrument did Ali Farka Touré, master of desert blues, play?",
    ["La guitare", "The guitar"], ["La kora", "The kora"], ["Le balafon", "The balafon"], ["La flûte", "The flute"],
    "Ce guitariste malien de Niafunké a prouvé que le blues était né en Afrique.",
    "This Malian guitarist from Niafunké proved that the blues was born in Africa."),

  Q("music", "medium",
    "Oumou Sangaré est la grande voix de quel style malien ?",
    "Oumou Sangaré is the great voice of which Malian style?",
    ["Le wassoulou", "Wassoulou"], ["Le mbalax", "Mbalax"], ["Le highlife", "Highlife"], ["Le raï", "Raï"],
    "Originaire du Wassoulou, au sud du Mali, elle chante aussi les droits des femmes.",
    "From Wassoulou in southern Mali, she also sings for women's rights."),

  Q("music", "medium",
    "Qui sont Amadou & Mariam ?",
    "Who are Amadou & Mariam?",
    ["Un duo malien non-voyant", "A blind Malian duo"], ["Deux frères sénégalais", "Two Senegalese brothers"], ["Un groupe nigérian", "A Nigerian band"], ["Un couple ivoirien", "An Ivorian couple"],
    "Ce couple malien, « l'ambassadeur aveugle du Mali », a joué avec Manu Chao et aux plus grands festivals.",
    "This Malian couple, 'the blind ambassadors of Mali', played with Manu Chao and at the biggest festivals."),

  Q("music", "medium",
    "Le raï, popularisé par Khaled et son « Aïcha », vient de quel pays ?",
    "Raï, popularized by Khaled and his 'Aïcha', comes from which country?",
    ["L'Algérie", "Algeria"], ["Le Maroc", "Morocco"], ["La Tunisie", "Tunisia"], ["L'Égypte", "Egypt"],
    "Né à Oran, le raï (« opinion ») était la voix de la jeunesse algérienne.",
    "Born in Oran, raï ('opinion') was the voice of Algerian youth."),

  Q("music", "medium",
    "Cesária Évora, la « diva aux pieds nus », chantait la morna de quel pays ?",
    "Cesária Évora, the 'Barefoot Diva', sang the morna of which country?",
    ["Le Cap-Vert", "Cape Verde"], ["L'Angola", "Angola"], ["Le Mozambique", "Mozambique"], ["La Guinée-Bissau", "Guinea-Bissau"],
    "Elle chantait pieds nus en solidarité avec les pauvres de son île.",
    "She sang barefoot in solidarity with the poor of her island."),

  Q("music", "medium",
    "Quel est le tube mondial de Manu Dibango, saxophoniste camerounais ?",
    "What is the worldwide hit of Manu Dibango, the Cameroonian saxophonist?",
    ["Soul Makossa", "Soul Makossa"], ["Pata Pata", "Pata Pata"], ["Aïcha", "Aïcha"], ["Yéké Yéké", "Yeke Yeke"],
    "Sorti en 1972, « Soul Makossa » a influencé le disco et même Michael Jackson.",
    "Released in 1972, 'Soul Makossa' influenced disco and even Michael Jackson."),

  Q("music", "medium",
    "Qui chante le célèbre « Pata Pata » ?",
    "Who sings the famous 'Pata Pata'?",
    ["Miriam Makeba", "Miriam Makeba"], ["Angélique Kidjo", "Angelique Kidjo"], ["Brenda Fassie", "Brenda Fassie"], ["Yvonne Chaka Chaka", "Yvonne Chaka Chaka"],
    "Enregistré en 1967, « Pata Pata » reste l'une des chansons africaines les plus connues au monde.",
    "Recorded in 1967, 'Pata Pata' remains one of the best-known African songs in the world."),

  Q("music", "medium",
    "Le groupe Tinariwen joue quel style de musique ?",
    "What style of music does the band Tinariwen play?",
    ["Le blues du désert touareg", "Tuareg desert blues"], ["La rumba congolaise", "Congolese rumba"], ["Le highlife ghanéen", "Ghanaian highlife"], ["Le raï algérien", "Algerian raï"],
    "Formé par des Touaregs du Sahara, Tinariwen a remporté un Grammy Award en 2012.",
    "Formed by Tuareg of the Sahara, Tinariwen won a Grammy Award in 2012."),

  Q("music", "medium",
    "Quel instrument joue Toumani Diabaté, légende malienne ?",
    "Which instrument does Toumani Diabaté, the Malian legend, play?",
    ["La kora", "The kora"], ["La guitare", "The guitar"], ["Le balafon", "The balafon"], ["Le ngoni", "The ngoni"],
    "Issu d'une lignée de 77 générations de joueurs de kora, il a collaboré avec Björk et Damon Albarn.",
    "From a lineage of 77 generations of kora players, he collaborated with Björk and Damon Albarn."),

  Q("music", "hard",
    "Qu'est-ce que le balafon ?",
    "What is the balafon?",
    ["Un xylophone en bois", "A wooden xylophone"], ["Une harpe", "A harp"], ["Une corne", "A horn"], ["Un tambour parlant", "A talking drum"],
    "Le balafon mandingue, avec ses calebasses résonnantes, est classé au patrimoine de l'UNESCO.",
    "The Manding balafon, with its resonating calabashes, is UNESCO-listed heritage."),

  Q("music", "hard",
    "Quel genre musical africain a été inscrit au patrimoine de l'UNESCO en 2021 ?",
    "Which African music genre was inscribed on UNESCO's heritage list in 2021?",
    ["La rumba congolaise", "Congolese rumba"], ["L'amapiano", "Amapiano"], ["Le coupé-décalé", "Coupé-décalé"], ["L'afrobeat", "Afrobeat"],
    "La rumba congolaise, berceau des stars comme Franco et Papa Wemba, unit les deux Congo.",
    "Congolese rumba, cradle of stars like Franco and Papa Wemba, unites the two Congos."),

  Q("music", "hard",
    "Quel album de Burna Boy a remporté le Grammy Award 2021 du meilleur album de musique du monde ?",
    "Which Burna Boy album won the 2021 Grammy for Best Global Music Album?",
    ["Twice as Tall", "Twice as Tall"], ["African Giant", "African Giant"], ["Love, Damini", "Love, Damini"], ["Outside", "Outside"],
    "Produit avec Diddy, « Twice as Tall » a consacré Burna Boy au sommet de la musique mondiale.",
    "Produced with Diddy, 'Twice as Tall' crowned Burna Boy at the top of world music."),

  Q("music", "hard",
    "Quelle artiste nigériane chante avec Wizkid sur le tube « Essence » ?",
    "Which Nigerian artist sings with Wizkid on the hit 'Essence'?",
    ["Tems", "Tems"], ["Ayra Starr", "Ayra Starr"], ["Tiwa Savage", "Tiwa Savage"], ["Simi", "Simi"],
    "« Essence » (2020) est entré dans l'histoire comme le premier tube afrobeats du Billboard Hot 100.",
    "'Essence' (2020) made history as the first afrobeats hit on the Billboard Hot 100."),

  Q("music", "hard",
    "Quel instrument jouait Hugh Masekela, légende sud-africaine du jazz ?",
    "Which instrument did Hugh Masekela, the South African jazz legend, play?",
    ["La trompette", "The trumpet"], ["Le saxophone", "The saxophone"], ["La guitare", "The guitar"], ["Le piano", "The piano"],
    "« Bra Hugh » a fui l'apartheid et sa trompette est devenue la voix de la liberté.",
    "'Bra Hugh' fled apartheid and his trumpet became the voice of freedom."),

  Q("music", "hard",
    "King Sunny Ade est le roi de quel genre nigérian ?",
    "King Sunny Ade is the king of which Nigerian genre?",
    ["Le juju", "Juju"], ["Le highlife", "Highlife"], ["L'afrobeat", "Afrobeat"], ["Le fuji", "Fuji"],
    "Le juju, avec ses guitares et tambours parlants, a fait de « KSA » la première star nigériane mondiale.",
    "Juju, with its guitars and talking drums, made 'KSA' Nigeria's first world star."),

  Q("music", "hard",
    "Papa Wemba, roi des sapeurs, venait de quel pays ?",
    "Papa Wemba, king of the sapeurs, came from which country?",
    ["La RD Congo", "DR Congo"], ["Le Congo-Brazzaville", "Republic of the Congo"], ["Le Cameroun", "Cameroon"], ["Le Gabon", "Gabon"],
    "Figure de la rumba et de la SAPE (l'élégance congolaise), il est mort en 2016 sur scène à Abidjan.",
    "A figure of rumba and SAPE (Congolese elegance), he died in 2016 on stage in Abidjan."),

  Q("music", "hard",
    "Qu'est-ce que le ngoni ?",
    "What is the ngoni?",
    ["Un luth traditionnel ouest-africain", "A traditional West African lute"], ["Un tambour", "A drum"], ["Une flûte", "A flute"], ["Une harpe", "A harp"],
    "Ancêtre du banjo américain, le ngoni accompagne les chasseurs et les griots du Mali.",
    "Ancestor of the American banjo, the ngoni accompanies Mali's hunters and griots."),


  /* ═══════════════ 🏆 SPORT / SPORTS (35) ═══════════════ */

  Q("sport", "easy",
    "Que signifie le sigle CAN dans le football africain ?",
    "What does AFCON stand for in African football?",
    ["Coupe d'Afrique des Nations", "Africa Cup of Nations"], ["Coupe d'Afrique du Nord", "North Africa Cup"], ["Championnat d'Afrique des Nations", "African Nations Championship"], ["Confédération Africaine des Nations", "African Nations Confederation"],
    "La CAN (AFCON en anglais) est le tournoi le plus suivi du continent, créé en 1957.",
    "AFCON is the continent's most watched tournament, created in 1957."),

  Q("sport", "easy",
    "Quel pays a remporté le plus de Coupes d'Afrique des Nations ?",
    "Which country has won the most Africa Cups of Nations?",
    ["L'Égypte", "Egypt"], ["Le Cameroun", "Cameroon"], ["Le Ghana", "Ghana"], ["Le Nigeria", "Nigeria"],
    "L'Égypte compte 7 titres, dont trois d'affilée (2006, 2008, 2010). Le Cameroun en a 5.",
    "Egypt has 7 titles, including three in a row (2006, 2008, 2010). Cameroon has 5."),

  Q("sport", "easy",
    "De quel pays vient Didier Drogba ?",
    "Which country is Didier Drogba from?",
    ["La Côte d'Ivoire", "Côte d'Ivoire"], ["Le Ghana", "Ghana"], ["Le Sénégal", "Senegal"], ["Le Cameroun", "Cameroon"],
    "Légende de Chelsea, Drogba a aussi joué un rôle de pacificateur dans son pays.",
    "A Chelsea legend, Drogba also played a peacemaker role in his country."),

  Q("sport", "easy",
    "De quel pays vient Sadio Mané ?",
    "Which country is Sadio Mané from?",
    ["Le Sénégal", "Senegal"], ["Le Mali", "Mali"], ["La Guinée", "Guinea"], ["La Gambie", "Gambia"],
    "Mané a offert au Sénégal sa première CAN en 2022 et finance des écoles et hôpitaux dans son village.",
    "Mané gave Senegal its first AFCON in 2022 and funds schools and hospitals in his village."),

  Q("sport", "easy",
    "De quel pays vient Mohamed Salah ?",
    "Which country is Mohamed Salah from?",
    ["L'Égypte", "Egypt"], ["Le Maroc", "Morocco"], ["L'Algérie", "Algeria"], ["La Tunisie", "Tunisia"],
    "Le « Pharaon égyptien » est l'une des plus grandes stars de Liverpool.",
    "The 'Egyptian King' is one of Liverpool's biggest stars."),

  Q("sport", "easy",
    "Quel pays africain a accueilli la première Coupe du monde sur le continent, en 2010 ?",
    "Which African country hosted the first World Cup on the continent, in 2010?",
    ["L'Afrique du Sud", "South Africa"], ["Le Maroc", "Morocco"], ["L'Égypte", "Egypt"], ["Le Nigeria", "Nigeria"],
    "L'Espagne a remporté ce Mondial 2010 marqué par les vuvuzelas et la chanson « Waka Waka ».",
    "Spain won that 2010 World Cup marked by vuvuzelas and the song 'Waka Waka'."),

  Q("sport", "easy",
    "Comment s'appelle la trompette bruyante emblème du Mondial 2010 ?",
    "What is the noisy horn emblem of the 2010 World Cup called?",
    ["La vuvuzela", "The vuvuzela"], ["Le djembé", "The djembe"], ["Le kazoo", "The kazoo"], ["Le cor de chasse", "The hunting horn"],
    "Son bourdonnement continu d'environ 127 décibels a marqué tous les supporters.",
    "Its continuous drone of about 127 decibels marked every fan."),

  Q("sport", "easy",
    "Quel est le surnom de l'équipe nationale du Sénégal ?",
    "What is the nickname of Senegal's national team?",
    ["Les Lions de la Téranga", "The Lions of Teranga"], ["Les Aigles", "The Eagles"], ["Les Éléphants", "The Elephants"], ["Les Éperviers", "The Sparrowhawks"],
    "La « téranga » est l'hospitalité légendaire du Sénégal.",
    "'Teranga' is Senegal's legendary hospitality."),

  Q("sport", "easy",
    "Quel est le surnom de l'équipe nationale du Nigeria ?",
    "What is the nickname of Nigeria's national team?",
    ["Les Super Eagles", "The Super Eagles"], ["Les Lions Indomptables", "The Indomitable Lions"], ["Les Black Stars", "The Black Stars"], ["Les Pharaons", "The Pharaohs"],
    "Les Super Eagles ont remporté la CAN à trois reprises (1980, 1994, 2013).",
    "The Super Eagles have won AFCON three times (1980, 1994, 2013)."),

  Q("sport", "easy",
    "Quel est le surnom de l'équipe nationale du Mali ?",
    "What is the nickname of Mali's national team?",
    ["Les Aigles", "The Eagles"], ["Les Lions", "The Lions"], ["Les Étalons", "The Stallions"], ["Les Écureuils", "The Squirrels"],
    "Les Aigles du Mali ont brillé en Coupe du monde U20, terminant 3es en 2015.",
    "Mali's Eagles shone at the U20 World Cup, finishing 3rd in 2015."),

  Q("sport", "easy",
    "Quel footballeur africain est le seul à avoir remporté le Ballon d'Or ?",
    "Which African footballer is the only one to have won the Ballon d'Or?",
    ["George Weah", "George Weah"], ["Samuel Eto'o", "Samuel Eto'o"], ["Didier Drogba", "Didier Drogba"], ["Sadio Mané", "Sadio Mané"],
    "Le Libérien George Weah a gagné le Ballon d'Or 1995 avant de devenir président de son pays.",
    "Liberia's George Weah won the 1995 Ballon d'Or before becoming his country's president."),

  Q("sport", "easy",
    "Tous les combien d'années se joue la Coupe d'Afrique des Nations ?",
    "How often is the Africa Cup of Nations played?",
    ["Tous les 2 ans", "Every 2 years"], ["Chaque année", "Every year"], ["Tous les 4 ans", "Every 4 years"], ["Tous les 3 ans", "Every 3 years"],
    "La CAN a lieu tous les deux ans, contrairement au Mondial qui se joue tous les quatre ans.",
    "AFCON takes place every two years, unlike the World Cup which is played every four years."),

  Q("sport", "medium",
    "Quel pays a remporté la CAN 2023 (jouée début 2024) à domicile ?",
    "Which country won AFCON 2023 (played in early 2024) at home?",
    ["La Côte d'Ivoire", "Côte d'Ivoire"], ["Le Nigeria", "Nigeria"], ["Le Sénégal", "Senegal"], ["Le Maroc", "Morocco"],
    "Les Éléphants, frôlant l'élimination en poules, ont réalisé un parcours de légende jusqu'au titre.",
    "The Elephants, nearly eliminated in the group stage, made a legendary run to the title."),

  Q("sport", "medium",
    "En quelle année (édition) le Sénégal a-t-il remporté sa première CAN ?",
    "In which edition did Senegal win its first AFCON?",
    ["2021 (jouée en 2022)", "2021 (played in 2022)"], ["2019", "2019"], ["2002", "2002"], ["2023", "2023"],
    "Sadio Mané a marqué le penalty de la victoire en finale contre l'Égypte.",
    "Sadio Mané scored the winning penalty in the final against Egypt."),

  Q("sport", "medium",
    "Quelle équipe africaine fut la première à atteindre les quarts de finale d'un Mondial (1990) ?",
    "Which African team was the first to reach a World Cup quarter-final (1990)?",
    ["Le Cameroun", "Cameroon"], ["Le Sénégal", "Senegal"], ["Le Ghana", "Ghana"], ["Le Nigeria", "Nigeria"],
    "Les Lions Indomptables de Roger Milla ont éliminé la Colombie avant de chuter face à l'Angleterre.",
    "Roger Milla's Indomitable Lions knocked out Colombia before falling to England."),

  Q("sport", "medium",
    "Quel champion du monde en titre le Sénégal a-t-il battu en match d'ouverture du Mondial 2002 ?",
    "Which defending world champion did Senegal beat in the 2002 World Cup opener?",
    ["La France", "France"], ["Le Brésil", "Brazil"], ["L'Allemagne", "Germany"], ["L'Argentine", "Argentina"],
    "Le but de Papa Bouba Diop (1-0) reste l'un des plus grands moments du football africain.",
    "Papa Bouba Diop's goal (1-0) remains one of the greatest moments in African football."),

  Q("sport", "medium",
    "Quel pays africain fut le premier demi-finaliste d'une Coupe du monde (2022) ?",
    "Which African country was the first World Cup semi-finalist (2022)?",
    ["Le Maroc", "Morocco"], ["Le Ghana", "Ghana"], ["Le Cameroun", "Cameroon"], ["Le Sénégal", "Senegal"],
    "Les Lions de l'Atlas ont éliminé la Belgique, l'Espagne et le Portugal au Qatar.",
    "The Atlas Lions eliminated Belgium, Spain and Portugal in Qatar."),

  Q("sport", "medium",
    "De quel pays vient Samuel Eto'o ?",
    "Which country is Samuel Eto'o from?",
    ["Le Cameroun", "Cameroon"], ["Le Nigeria", "Nigeria"], ["Le Ghana", "Ghana"], ["La Côte d'Ivoire", "Côte d'Ivoire"],
    "Quatre fois joueur africain de l'année, Eto'o a gagné la Ligue des champions avec le Barça et l'Inter.",
    "Four-time African Player of the Year, Eto'o won the Champions League with Barça and Inter."),

  Q("sport", "medium",
    "Quelle célébration a rendu Roger Milla célèbre au Mondial 1990 ?",
    "Which celebration made Roger Milla famous at the 1990 World Cup?",
    ["La danse au poteau de corner", "The corner flag dance"], ["Le salto arrière", "The backflip"], ["Le genou au sol", "The knee slide"], ["La danse du robot", "The robot dance"],
    "À 38 ans, ses 4 buts et sa danse du makossa au corner ont fait le tour du monde.",
    "At 38, his 4 goals and his makossa dance at the corner flag went around the world."),

  Q("sport", "medium",
    "Dans quelle discipline Eliud Kipchoge est-il une légende ?",
    "In which discipline is Eliud Kipchoge a legend?",
    ["Le marathon", "The marathon"], ["Le 100 mètres", "The 100 metres"], ["Le saut en longueur", "The long jump"], ["Le cyclisme", "Cycling"],
    "Le Kenyan est le premier homme à avoir couru un marathon en moins de 2 heures (exhibition, 2019).",
    "The Kenyan is the first man to run a marathon in under 2 hours (exhibition, 2019)."),

  Q("sport", "medium",
    "De quel pays vient la légende de l'athlétisme Haile Gebrselassie ?",
    "Which country is athletics legend Haile Gebrselassie from?",
    ["L'Éthiopie", "Ethiopia"], ["Le Kenya", "Kenya"], ["Le Maroc", "Morocco"], ["L'Érythrée", "Eritrea"],
    "Double champion olympique du 10 000 m, il a battu 27 records du monde.",
    "A two-time Olympic 10,000 m champion, he broke 27 world records."),

  Q("sport", "medium",
    "De quel pays vient la légende NBA Hakeem Olajuwon ?",
    "Which country is NBA legend Hakeem Olajuwon from?",
    ["Le Nigeria", "Nigeria"], ["Le Sénégal", "Senegal"], ["Le Cameroun", "Cameroon"], ["La RD Congo", "DR Congo"],
    "« The Dream », double champion NBA avec Houston, est considéré comme l'un des meilleurs pivots de l'histoire.",
    "'The Dream', a two-time NBA champion with Houston, is considered one of the greatest centers ever."),

  Q("sport", "medium",
    "Quel pays a remporté la CAN 2019 ?",
    "Which country won AFCON 2019?",
    ["L'Algérie", "Algeria"], ["Le Sénégal", "Senegal"], ["Le Nigeria", "Nigeria"], ["La Tunisie", "Tunisia"],
    "Les Fennecs de Riyad Mahrez ont battu le Sénégal 1-0 en finale.",
    "Riyad Mahrez's Fennecs beat Senegal 1-0 in the final."),

  Q("sport", "medium",
    "Combien de fois Yaya Touré a-t-il été élu joueur africain de l'année ?",
    "How many times was Yaya Touré voted African Player of the Year?",
    ["4 fois", "4 times"], ["2 fois", "2 times"], ["3 fois", "3 times"], ["5 fois", "5 times"],
    "Quatre titres consécutifs (2011-2014) pour le milieu ivoirien de Manchester City, un record partagé avec Eto'o.",
    "Four consecutive titles (2011-2014) for the Ivorian Manchester City midfielder, a record shared with Eto'o."),

  Q("sport", "medium",
    "Contre quelle équipe le Ghana a-t-il perdu son quart de finale historique du Mondial 2010 ?",
    "Against which team did Ghana lose its historic 2010 World Cup quarter-final?",
    ["L'Uruguay", "Uruguay"], ["Le Brésil", "Brazil"], ["L'Allemagne", "Germany"], ["L'Espagne", "Spain"],
    "Après la main de Suárez sur la ligne et le penalty raté de Gyan, le Ghana s'inclina aux tirs au but.",
    "After Suárez's handball on the line and Gyan's missed penalty, Ghana lost on penalties."),

  Q("sport", "medium",
    "De quel pays vient Abedi Pelé ?",
    "Which country is Abedi Pelé from?",
    ["Le Ghana", "Ghana"], ["Le Nigeria", "Nigeria"], ["Le Cameroun", "Cameroon"], ["Le Sénégal", "Senegal"],
    "Trois fois joueur africain de l'année, il a gagné la Ligue des champions 1993 avec Marseille.",
    "Three-time African Player of the Year, he won the 1993 Champions League with Marseille."),

  Q("sport", "medium",
    "Riyad Mahrez est l'international star de quel pays ?",
    "Riyad Mahrez is the star international of which country?",
    ["L'Algérie", "Algeria"], ["Le Maroc", "Morocco"], ["La Tunisie", "Tunisia"], ["L'Égypte", "Egypt"],
    "Champion d'Afrique 2019 et de Premier League avec Leicester et Manchester City.",
    "African champion in 2019 and Premier League winner with Leicester and Manchester City."),

  Q("sport", "medium",
    "De quel pays vient le défenseur Kalidou Koulibaly ?",
    "Which country is defender Kalidou Koulibaly from?",
    ["Le Sénégal", "Senegal"], ["Le Mali", "Mali"], ["La Guinée", "Guinea"], ["La Côte d'Ivoire", "Côte d'Ivoire"],
    "Né en France, il a choisi le Sénégal et a soulevé la CAN 2021 comme capitaine.",
    "Born in France, he chose Senegal and lifted AFCON 2021 as captain."),

  Q("sport", "hard",
    "Quel fut le score de la finale de la CAN 2023 entre la Côte d'Ivoire et le Nigeria ?",
    "What was the score of the AFCON 2023 final between Côte d'Ivoire and Nigeria?",
    ["2-1", "2-1"], ["1-0", "1-0"], ["3-1", "3-1"], ["2-0", "2-0"],
    "Menés à la mi-temps, les Éléphants ont renversé le Nigeria grâce à Kessié et Haller.",
    "Trailing at half-time, the Elephants turned the game around thanks to Kessié and Haller."),

  Q("sport", "hard",
    "Dans quel pays est né la star NBA Joel Embiid ?",
    "In which country was NBA star Joel Embiid born?",
    ["Le Cameroun", "Cameroon"], ["Le Nigeria", "Nigeria"], ["Le Sénégal", "Senegal"], ["La RD Congo", "DR Congo"],
    "MVP NBA 2023, Embiid a découvert le basket à 15 ans à Yaoundé.",
    "2023 NBA MVP, Embiid only discovered basketball at 15 in Yaoundé."),

  Q("sport", "hard",
    "Les parents de Giannis Antetokounmpo, le « Greek Freak », viennent de quel pays africain ?",
    "Giannis Antetokounmpo's parents, the 'Greek Freak', come from which African country?",
    ["Le Nigeria", "Nigeria"], ["Le Ghana", "Ghana"], ["Le Sénégal", "Senegal"], ["Le Cameroun", "Cameroon"],
    "Double MVP et champion NBA 2021, Giannis reste très attaché à ses racines nigérianes.",
    "Two-time MVP and 2021 NBA champion, Giannis remains very attached to his Nigerian roots."),

  Q("sport", "hard",
    "Sur quelle distance Caster Semenya est-elle double championne olympique ?",
    "Over which distance is Caster Semenya a two-time Olympic champion?",
    ["Le 800 mètres", "The 800 metres"], ["Le 100 mètres", "The 100 metres"], ["Le marathon", "The marathon"], ["Le 400 m haies", "The 400 m hurdles"],
    "La Sud-Africaine a dominé le 800 m à Londres 2012 et Rio 2016.",
    "The South African dominated the 800 m at London 2012 and Rio 2016."),

  Q("sport", "hard",
    "Kenenisa Bekele a détenu les records du monde de quelles distances ?",
    "Kenenisa Bekele held world records over which distances?",
    ["5 000 m et 10 000 m", "5,000 m and 10,000 m"], ["100 m et 200 m", "100 m and 200 m"], ["400 m et 800 m", "400 m and 800 m"], ["1 500 m et 3 000 m", "1,500 m and 3,000 m"],
    "L'Éthiopien est considéré comme l'un des plus grands coureurs de fond de tous les temps.",
    "The Ethiopian is considered one of the greatest long-distance runners of all time."),

  Q("sport", "hard",
    "Quel pays africain a remporté le premier titre olympique de football (1996) ?",
    "Which African country won the first Olympic football title (1996)?",
    ["Le Nigeria", "Nigeria"], ["Le Cameroun", "Cameroon"], ["Le Ghana", "Ghana"], ["L'Égypte", "Egypt"],
    "Les Super Eagles ont renversé l'Argentine 3-2 en finale à Atlanta. Le Cameroun a suivi en 2000.",
    "The Super Eagles came back to beat Argentina 3-2 in the Atlanta final. Cameroon followed in 2000."),

  Q("sport", "hard",
    "Quelle équipe a remporté la CAN 2012 aux tirs au but contre la Côte d'Ivoire ?",
    "Which team won AFCON 2012 on penalties against Côte d'Ivoire?",
    ["La Zambie", "Zambia"], ["Le Ghana", "Ghana"], ["Le Nigeria", "Nigeria"], ["Le Mali", "Mali"],
    "Victoire émouvante à Libreville, près du lieu du crash aérien de 1993 qui avait décimé l'équipe zambienne.",
    "A moving victory in Libreville, near the site of the 1993 plane crash that decimated the Zambian team."),

  /* ═══════════════ 🌱 NATURE / NATURE (35) ═══════════════ */

  Q("nature", "easy",
    "Quel est le plus grand animal terrestre du monde ?",
    "What is the largest land animal in the world?",
    ["L'éléphant d'Afrique", "The African elephant"], ["L'hippopotame", "The hippopotamus"], ["La girafe", "The giraffe"], ["Le rhinocéros blanc", "The white rhinoceros"],
    "Un éléphant d'Afrique peut peser jusqu'à 6 tonnes. Malheureusement braconné pour son ivoire.",
    "An African elephant can weigh up to 6 tonnes. Sadly poached for its ivory."),

  Q("nature", "easy",
    "Quel est l'animal le plus grand (en hauteur) du monde ?",
    "What is the tallest animal in the world?",
    ["La girafe", "The giraffe"], ["L'éléphant", "The elephant"], ["L'autruche", "The ostrich"], ["Le dromadaire", "The dromedary"],
    "La girafe mesure jusqu'à 5,5 m et sa langue peut atteindre 50 cm.",
    "A giraffe can reach 5.5 m and its tongue up to 50 cm."),

  Q("nature", "easy",
    "Quel est l'animal terrestre le plus rapide du monde ?",
    "What is the fastest land animal in the world?",
    ["Le guépard", "The cheetah"], ["Le lion", "The lion"], ["Le léopard", "The leopard"], ["L'antilope", "The antelope"],
    "Le guépard atteint 110 km/h en pointe, mais seulement sur quelques centaines de mètres.",
    "The cheetah reaches 110 km/h at top speed, but only over a few hundred metres."),

  Q("nature", "easy",
    "Quel animal est surnommé le « roi de la savane » ?",
    "Which animal is nicknamed the 'king of the savanna'?",
    ["Le lion", "The lion"], ["L'éléphant", "The elephant"], ["Le léopard", "The leopard"], ["Le buffle", "The buffalo"],
    "Contrairement aux autres grands félins, les lions vivent en groupes : les hardes.",
    "Unlike other big cats, lions live in groups: prides."),

  Q("nature", "easy",
    "Quel animal a des rayures noires et blanches uniques, comme des empreintes digitales ?",
    "Which animal has unique black and white stripes, like fingerprints?",
    ["Le zèbre", "The zebra"], ["La girafe", "The giraffe"], ["L'okapi", "The okapi"], ["Le gnou", "The wildebeest"],
    "Aucun zèbre n'a le même motif de rayures qu'un autre.",
    "No two zebras have the same stripe pattern."),

  Q("nature", "easy",
    "Les lémuriens ne vivent à l'état sauvage que dans quel pays ?",
    "Lemurs live in the wild only in which country?",
    ["Madagascar", "Madagascar"], ["Le Kenya", "Kenya"], ["L'Afrique du Sud", "South Africa"], ["La Tanzanie", "Tanzania"],
    "90 % des espèces de Madagascar n'existent nulle part ailleurs sur Terre.",
    "90% of Madagascar's species exist nowhere else on Earth."),

  Q("nature", "easy",
    "Quel arbre, surnommé « arbre de vie », stocke l'eau dans son immense tronc ?",
    "Which tree, nicknamed the 'tree of life', stores water in its huge trunk?",
    ["Le baobab", "The baobab"], ["L'acacia", "The acacia"], ["Le palmier", "The palm tree"], ["Le manguier", "The mango tree"],
    "Un baobab peut stocker jusqu'à 120 000 litres d'eau et vivre plus de mille ans.",
    "A baobab can store up to 120,000 litres of water and live over a thousand years."),

  Q("nature", "easy",
    "Quel est le plus grand oiseau du monde ?",
    "What is the largest bird in the world?",
    ["L'autruche", "The ostrich"], ["L'aigle", "The eagle"], ["Le flamant rose", "The flamingo"], ["Le marabout", "The marabou"],
    "L'autruche ne vole pas, mais court à 70 km/h et pond les plus gros œufs du monde.",
    "The ostrich cannot fly, but runs at 70 km/h and lays the largest eggs in the world."),

  Q("nature", "easy",
    "Dans quel pays peut-on observer les gorilles de montagne ?",
    "In which country can you observe mountain gorillas?",
    ["Le Rwanda", "Rwanda"], ["Le Maroc", "Morocco"], ["L'Égypte", "Egypt"], ["Le Botswana", "Botswana"],
    "Les gorilles de montagne vivent dans les montagnes des Virunga (Rwanda, Ouganda, RD Congo).",
    "Mountain gorillas live in the Virunga mountains (Rwanda, Uganda, DR Congo)."),

  Q("nature", "easy",
    "Quel grand reptile, redouté des pêcheurs, vit dans les fleuves africains ?",
    "Which large reptile, feared by fishermen, lives in African rivers?",
    ["Le crocodile du Nil", "The Nile crocodile"], ["Le varan", "The monitor lizard"], ["Le python", "The python"], ["Le caméléon", "The chameleon"],
    "Le crocodile du Nil peut dépasser 5 mètres et vivre 70 ans.",
    "The Nile crocodile can exceed 5 metres and live 70 years."),

  Q("nature", "easy",
    "Pour quel cri la hyène tachetée est-elle célèbre ?",
    "What call is the spotted hyena famous for?",
    ["Son rire", "Its laugh"], ["Son rugissement", "Its roar"], ["Son sifflement", "Its whistle"], ["Son chant", "Its song"],
    "Le « rire » de la hyène sert en réalité à communiquer avec son clan.",
    "The hyena's 'laugh' is actually used to communicate with its clan."),

  Q("nature", "medium",
    "Dans quel parc a lieu la grande migration des gnous ?",
    "In which park does the great wildebeest migration take place?",
    ["Le Serengeti", "The Serengeti"], ["Le Kruger", "Kruger"], ["L'Okavango", "The Okavango"], ["L'Amboseli", "Amboseli"],
    "Près de 2 millions de gnous et zèbres traversent chaque année le Serengeti et le Masai Mara.",
    "Nearly 2 million wildebeest and zebras cross the Serengeti and Masai Mara each year."),

  Q("nature", "medium",
    "Dans quel pays se trouve le delta de l'Okavango ?",
    "In which country is the Okavango Delta?",
    ["Le Botswana", "Botswana"], ["La Namibie", "Namibia"], ["La Zambie", "Zambia"], ["Le Zimbabwe", "Zimbabwe"],
    "Ce delta intérieur, classé à l'UNESCO, se jette dans le désert du Kalahari sans jamais atteindre la mer.",
    "This inland delta, UNESCO-listed, flows into the Kalahari Desert without ever reaching the sea."),

  Q("nature", "medium",
    "Quel est le plus vieux désert du monde ?",
    "What is the oldest desert in the world?",
    ["Le Namib", "The Namib"], ["Le Sahara", "The Sahara"], ["Le Kalahari", "The Kalahari"], ["Le Gobi", "The Gobi"],
    "Le Namib, en Namibie, existe depuis au moins 55 millions d'années.",
    "The Namib, in Namibia, has existed for at least 55 million years."),

  Q("nature", "medium",
    "Quelle est la deuxième plus grande forêt tropicale du monde ?",
    "What is the second largest rainforest in the world?",
    ["La forêt du bassin du Congo", "The Congo Basin rainforest"], ["L'Amazonie", "The Amazon"], ["La forêt de Bornéo", "The Borneo rainforest"], ["La taïga", "The taiga"],
    "Le bassin du Congo absorbe plus de CO2 qu'il n'en émet : c'est le « deuxième poumon » de la planète.",
    "The Congo Basin absorbs more CO2 than it emits: it is the planet's 'second lung'."),

  Q("nature", "medium",
    "De quel lac le Nil Blanc prend-il sa source ?",
    "From which lake does the White Nile take its source?",
    ["Le lac Victoria", "Lake Victoria"], ["Le lac Tanganyika", "Lake Tanganyika"], ["Le lac Tchad", "Lake Chad"], ["Le lac Malawi", "Lake Malawi"],
    "Le Nil Blanc naît du lac Victoria, le Nil Bleu du lac Tana en Éthiopie.",
    "The White Nile rises from Lake Victoria, the Blue Nile from Lake Tana in Ethiopia."),

  Q("nature", "medium",
    "Le Kilimandjaro est en réalité...",
    "Mount Kilimanjaro is actually a...",
    ["Un volcan endormi", "A dormant volcano"], ["Un volcan actif", "An active volcano"], ["Une chaîne plissée", "A fold mountain range"], ["Un plateau", "A plateau"],
    "Malgré sa position près de l'équateur, son sommet est coiffé de glaciers qui fondent vite.",
    "Despite its position near the equator, its summit is capped with fast-melting glaciers."),

  Q("nature", "medium",
    "« Mosi-oa-Tunya », la « fumée qui gronde », désigne quelle merveille naturelle ?",
    "'Mosi-oa-Tunya', 'the smoke that thunders', refers to which natural wonder?",
    ["Les chutes Victoria", "Victoria Falls"], ["Le mont Kenya", "Mount Kenya"], ["Le lac Malawi", "Lake Malawi"], ["Le volcan Nyiragongo", "Mount Nyiragongo"],
    "Le grondement des chutes Victoria s'entend à 40 km à la ronde en saison des pluies.",
    "The roar of Victoria Falls can be heard 40 km away in the rainy season."),

  Q("nature", "medium",
    "Lequel de ces animaux ne fait PAS partie des « Big Five » ?",
    "Which of these animals is NOT part of the 'Big Five'?",
    ["La girafe", "The giraffe"], ["Le lion", "The lion"], ["Le léopard", "The leopard"], ["Le buffle", "The buffalo"],
    "Les Big Five (lion, léopard, éléphant, rhinocéros, buffle) étaient les animaux les plus difficiles à chasser.",
    "The Big Five (lion, leopard, elephant, rhinoceros, buffalo) were the hardest animals to hunt."),

  Q("nature", "medium",
    "Comment appelle-t-on un groupe de lions ?",
    "What is a group of lions called?",
    ["Une harde", "A pride"], ["Un troupeau", "A herd"], ["Une meute", "A pack"], ["Un essaim", "A swarm"],
    "Une harde compte en général quelques lionnes, leurs petits et un ou deux mâles.",
    "A pride usually consists of a few lionesses, their cubs and one or two males."),

  Q("nature", "medium",
    "Quel petit renard du Sahara a des oreilles démesurées ?",
    "Which small Sahara fox has oversized ears?",
    ["Le fennec", "The fennec"], ["Le chacal", "The jackal"], ["La hyène", "The hyena"], ["Le lycaon", "The African wild dog"],
    "Les oreilles du fennec dissipent la chaleur et entendent les proies sous le sable.",
    "The fennec's ears dissipate heat and hear prey under the sand."),

  Q("nature", "medium",
    "Quel canidé africain est surnommé le « loup peint » ?",
    "Which African canid is nicknamed the 'painted wolf'?",
    ["Le lycaon", "The African wild dog"], ["La hyène", "The hyena"], ["Le chacal", "The jackal"], ["Le fennec", "The fennec"],
    "Le lycaon est l'un des mammifères les plus menacés d'Afrique, malgré un taux de réussite de chasse record.",
    "The African wild dog is one of Africa's most endangered mammals, despite a record hunting success rate."),

  Q("nature", "medium",
    "Près de quelle ville d'Afrique du Sud vit une célèbre colonie de manchots ?",
    "Near which South African city does a famous penguin colony live?",
    ["Le Cap", "Cape Town"], ["Durban", "Durban"], ["Johannesburg", "Johannesburg"], ["Port Elizabeth", "Gqeberha"],
    "Les manchots du Cap paradent sur la plage de Boulders Beach, à côté des baigneurs.",
    "African penguins strut on Boulders Beach, right next to swimmers."),

  Q("nature", "medium",
    "Sur quel lac du Kenya se rassemblent d'immenses colonies de flamants roses ?",
    "On which Kenyan lake do huge flamingo colonies gather?",
    ["Le lac Nakuru", "Lake Nakuru"], ["Le lac Victoria", "Lake Victoria"], ["Le lac Tchad", "Lake Chad"], ["Le lac Tanganyika", "Lake Tanganyika"],
    "Les flamants se nourrissent des algues des lacs alcalins de la vallée du Rift.",
    "Flamingos feed on the algae of the Rift Valley's alkaline lakes."),

  Q("nature", "medium",
    "Combien de bosses possède un dromadaire ?",
    "How many humps does a dromedary have?",
    ["Une", "One"], ["Deux", "Two"], ["Trois", "Three"], ["Aucune", "None"],
    "Le dromadaire (une bosse) peuple le Sahara ; le chameau de Bactriane (deux bosses) vit en Asie.",
    "The dromedary (one hump) populates the Sahara; the Bactrian camel (two humps) lives in Asia."),

  Q("nature", "medium",
    "Combien de temps un baobab peut-il vivre ?",
    "How long can a baobab live?",
    ["Plus de 1 000 ans", "Over 1,000 years"], ["50 ans", "50 years"], ["100 ans", "100 years"], ["200 ans", "200 years"],
    "Certains baobabs auraient plus de 2 000 ans. Au Sahel, on s'y rassemble pour palabrer.",
    "Some baobabs are believed to be over 2,000 years old. In the Sahel, people gather under them to talk."),

  Q("nature", "medium",
    "Le lac Malawi est mondialement célèbre pour...",
    "Lake Malawi is world-famous for...",
    ["Ses poissons cichlidés multicolores", "Its multicolored cichlid fish"], ["Ses crocodiles albinos", "Its albino crocodiles"], ["Ses hippopotames roses", "Its pink hippos"], ["Ses dauphins d'eau douce", "Its freshwater dolphins"],
    "Le lac abrite plus d'espèces de poissons que tout autre lac du monde.",
    "The lake hosts more fish species than any other lake in the world."),

  Q("nature", "medium",
    "Quel grand félin ne sait pas rugir ?",
    "Which big cat cannot roar?",
    ["Le guépard", "The cheetah"], ["Le lion", "The lion"], ["Le léopard", "The leopard"], ["La lionne", "The lioness"],
    "Le guépard ronronne comme un chat domestique, mais ne peut pas rugir.",
    "The cheetah purrs like a house cat, but cannot roar."),

  Q("nature", "hard",
    "Quel est le deuxième lac le plus profond du monde ?",
    "What is the second deepest lake in the world?",
    ["Le lac Tanganyika", "Lake Tanganyika"], ["Le lac Victoria", "Lake Victoria"], ["Le lac Malawi", "Lake Malawi"], ["Le lac Baïkal", "Lake Baikal"],
    "Avec 1 470 m de fond, le Tanganyika n'est dépassé que par le Baïkal (1 642 m).",
    "At 1,470 m deep, Tanganyika is surpassed only by Baikal (1,642 m)."),

  Q("nature", "hard",
    "Quel est le troisième plus long fleuve d'Afrique ?",
    "What is the third longest river in Africa?",
    ["Le Niger", "The Niger"], ["Le Zambèze", "The Zambezi"], ["L'Orange", "The Orange"], ["Le Limpopo", "The Limpopo"],
    "Le Niger (4 180 km) suit un étrange coude : il naît près de l'océan mais s'en éloigne avant d'y revenir.",
    "The Niger (4,180 km) follows a strange bend: it rises near the ocean but flows away before returning to it."),

  Q("nature", "hard",
    "Quel grand mammifère herbivore est réputé être l'un des plus dangereux d'Afrique ?",
    "Which large herbivorous mammal is reputed to be one of the most dangerous in Africa?",
    ["L'hippopotame", "The hippopotamus"], ["La girafe", "The giraffe"], ["Le zèbre", "The zebra"], ["L'autruche", "The ostrich"],
    "Malgré son air placide, l'hippopotame est extrêmement territorial et très rapide sur terre.",
    "Despite its placid look, the hippo is extremely territorial and very fast on land."),

  Q("nature", "hard",
    "Les singes géladas, au cœur rouge, ne vivent que dans quel pays ?",
    "Gelada monkeys, with their red hearts, live only in which country?",
    ["L'Éthiopie", "Ethiopia"], ["Le Kenya", "Kenya"], ["Madagascar", "Madagascar"], ["Le Maroc", "Morocco"],
    "Les géladas broutent l'herbe des hauts plateaux des monts Simien, jusqu'à 4 000 m d'altitude.",
    "Geladas graze the high plateaus of the Simien Mountains, up to 4,000 m in altitude."),

  Q("nature", "hard",
    "Dans quel pays se trouve la chaîne du Drakensberg ?",
    "In which country is the Drakensberg mountain range?",
    ["L'Afrique du Sud", "South Africa"], ["La Namibie", "Namibia"], ["Le Kenya", "Kenya"], ["L'Éthiopie", "Ethiopia"],
    "Le Drakensberg, « montagne des dragons », culmine à 3 482 m.",
    "The Drakensberg, 'dragon mountain', rises to 3,482 m."),

  Q("nature", "hard",
    "De quel animal l'okapi, à rayures sur les pattes, est-il le plus proche parent ?",
    "The okapi, with its striped legs, is most closely related to which animal?",
    ["La girafe", "The giraffe"], ["Le zèbre", "The zebra"], ["L'antilope", "The antelope"], ["Le cheval", "The horse"],
    "Découvert en 1901 dans la forêt d'Ituri (RD Congo), l'okapi est le seul parent vivant de la girafe.",
    "Discovered in 1901 in the Ituri forest (DR Congo), the okapi is the giraffe's only living relative."),

  Q("nature", "hard",
    "L'addax, antilope blanche en danger critique, vit dans quelle région ?",
    "The addax, a critically endangered white antelope, lives in which region?",
    ["Le Sahara et le Sahel", "The Sahara and the Sahel"], ["La forêt du Congo", "The Congo forest"], ["La savane du Kenya", "The Kenyan savanna"], ["Le delta de l'Okavango", "The Okavango Delta"],
    "L'addax survit des mois sans boire grâce à l'eau des plantes du désert.",
    "The addax survives months without drinking thanks to the water in desert plants."),
]

module.exports = { QUESTIONS };
